### ISSUE TITLE
Use quiche API for trace_id once it is exposed

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty-incubator-codec-quic#12]
See https://github.com/cloudflare/quiche/issues/713

**Comment by normanmaurer** [comment]
https://github.com/cloudflare/quiche/pull/724

**Comment by vasantteja** [comment]
They already pushed the changes at cloudflare side can I work on this. Is there any sample of code which I can use as reference for my implementation. I have some free time over this weekend and I can spend on this one. Please don't mind.

**Comment by normanmaurer** [comment]
Yes sure 👌

**Comment by normanmaurer** [comment]
that said its only present in `master` atm... so no release yet to pick up. That said we can do the preparation now

**Comment by vasantteja** [comment]
@normanmaurer  I spent a considerable time in understanding the changes that needs to done. Here is my understanding. We need to make netty c code to get trace id and expose it either in nativejndimethods or quiche Java code where we can pick up this trace id and use it everywhere. Please let me know if I got it right.

**Comment by normanmaurer** [comment]
yes... it would be exposed in `Quiche`.

**Comment by vasantteja** [comment]
@normanmaurer Is it merged to the master branch?
