### ISSUE TITLE
How often is QuicStreamChannel created?

### ISSUE THREAD

**Issue by chenzhiguo** [netty/netty-incubator-codec-quic#128]
In the RPC framework invocation scenario, do you need to create a `QuicStreamChannel` for each request?
In the case of heavy traffic, I don't think this is an efficient approach. But if you reuse the original `QuicStreamChannel`, how do you cache it?

**Comment by normanmaurer** [comment]
This depends on the protocol that sits on top of QUIC... if we are talking about HTT3 each new request / response will use a new stream (as required by the spec).

**Comment by normanmaurer** [comment]
Other protocols may use "long-living" streams and use these more like "TCP connections" that are long living.

**Comment by chenzhiguo** [comment]
Can I understand that? The protocol on QUIC that I customized can completely define whether `QuicStreamChannel ` can be reused or not, or the life cycle of `QuicStreamChannel `, there is no limit in QUIC protocol.
For example, I can cache a portion of `QuicStreamChannel ` to improve performance, similar to the thread pool model.

**Comment by normanmaurer** [comment]
Think of a `QuicStreamChannel` as a `SocketChannel`... its just a stream of bytes. So how you multiplex your protocol on top of it is up to you.
