### ISSUE TITLE
Build for Android

### ISSUE THREAD

**Issue by JBou** [netty/netty-incubator-codec-quic#184]
Hello, I'm really looking forward into this awesome project, especially the connection migration. I tried the example code on windows, it's really nice. 

Is there a chance to build this package for android? Would like to use it in an android app. I already tried to build the windows package myself, and wanted to add an android build later, but I'm still struggling with building BetterSSL using cmake, cl.exe and so on... 

Do you have any plans to add support for Android in the near future?

**Comment by normanmaurer** [comment]
I honestly have no plans for android atm

**Comment by normanmaurer** [comment]
That said if there is anyone who want to contribute this I am happy to review it.

**Comment by JBou** [comment]
Thanks for your answer.
I'm already working on this, I'm making good progress.

I successfully compiled the native lib and packaged it. Now I need to pack it into a sample apk and test it out on the device.

After testing it on the device and cleaning up the build process i can make a PR to look over it.

**Comment by normanmaurer** [comment]
@JBou just to clarify we are not interested to "host" the apk... we are only interested in make it compile for android use.

**Comment by JBou** [comment]
I'm just making an apk to test it out, a personal sample project. 

My intention was to create a maven profile for android and building a "jar" with an android classifier, just like it's already for linux, windows and osx.
So someone could use this dependency on another project. I hoped it could be deployed to the maven repository then. Aren't you interested in this?

If not, someone would always have to get the newest source code, build it himself, and upload it to his own repository. Changes in this project would have to be updated manually every time. Can't we add a ci-workflow for this?

**Comment by normanmaurer** [comment]
If it can be supported by GitHub I guess we could. Never tried this

**Comment by JBou** [comment]
Thanks a lot! I will try to get this to work in the coming days.
