### ISSUE TITLE
How do I send a ping frame and a goaway frame?

### ISSUE THREAD

**Issue by vovgou** [netty/netty-incubator-codec-quic#250]
Hi,
What should I do if I want to keep the connection alive? I did not find a way to send a ping frame.
In addition, I may also want to send and receive a goaway frame, is this possible?
Thank you!

**Comment by normanmaurer** [comment]
At the moment its not possible to explicit send a PING frame. See also: https://github.com/cloudflare/quiche/issues/635

For a go away frame you would use `shutdownOutput(err,....)`. Check the javadocs for `QuicStreamChannel`

**Comment by normanmaurer** [comment]
This is not done yet
