### ISSUE TITLE
Sending ByteBuf example

### ISSUE THREAD

**Issue by QNENet** [netty/netty-incubator-codec-quic#251]
The netty quic example uses HTTP 0.9 as an application protocol but seems to, in effect, send and receive a bytebuf msg.
Does the application protocol have an effect on the byteBuf?
Is the underlying quic/quiche code capable of handling plain byte payloads rather than http?
I have tried altering the netty example to just wrap a byte array and set the application protocol to null, but this does not work. (Using a LengthFieldBasedFrameDecoder).
Is the use of Unpooled.copiedBuffer significant?
If it is possible to just send byteBufs in a stream how should this be done?
An example or comment in the docs might assist users to handle plain byte/bytebuf payloads if the capability exists.

**Comment by QNENet** [comment]
On investigation it seems http is baked into the codec although I have not found where http 0.9 is handled.
Possibility is to use the new netty/quic datagram extension.

**Comment by normanmaurer** [comment]
@QNENet the QUIC implementation really only cares about bytes. Using "HTTP/0.9" was just an example. The important bit is that both peers need to agree on the protocol that is used.
