### ISSUE TITLE
More fine-grained exception hierarchy

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty-incubator-codec-quic#26]
At the moment we basically only use `SSLException`, `SSLHandshakeException` and `IOException` for QUIC. It would be better to be a bit more fine-grained here to make it easier for people to understand why something failed.

**Comment by kachayev** [comment]
Should the structure of exception follow the same structure quiche has for [error codes](https://github.com/cloudflare/quiche/blob/a8dc7f106064f3b9188015f14283a8633b8913a8/src/lib.rs#L335-L380)? Or do you have something different on mind?

**Comment by normanmaurer** [comment]
Yeah maybe we could just include the exact error as an enum int the message.

**Comment by kachayev** [comment]
I'll take a stab on this one tomorrow.
