### ISSUE TITLE
QuicStreamAddress feature request (real SocketAddress)

### ISSUE THREAD

**Issue by remmerw** [netty/netty-incubator-codec-quic#263]
Does it make sense, that the QuicStreamAddress  also contains the real SocketAddress beseides the long identifier?
Would be nice for my project.

**Comment by normanmaurer** [comment]
@remmerw not sure the really would make sense as a quic connection could migrate to another socket during life-time

**Comment by remmerw** [comment]
And? When asking for the stream address, alway getting the current socket
address.
But I guess there is no API for it (I mean from quiche)

Am Mi., 5. Mai 2021 um 10:11 Uhr schrieb Norman Maurer <
***@***.***>:

**Comment by normanmaurer** [comment]
Maybe you can help me and explain why it would be useful for you and I can better understand how to help :) ?

**Comment by remmerw** [comment]
Yes, I will try to explain.
I am working on a decentralized application (IPFS context). Peers telling
each other their IP addresses, so that
the other peer knows its "real" IP address (is of course not working in all
cases).
So when there is a connection to a peer (probably behind a NAT), I will
tell him by evaluating the
"remoteAddress". The other peer knows after asking several other peers,
whether he has a public ip address
or not. In case of not, other measurements have to be taken, so that 2
peers behind a NAT can talk to each
other.
Ok this is not well explained, but I hop you got the idea.
Is there an API on QUICHE to get the information? (I have not found it)


Am Mi., 5. Mai 2021 um 15:02 Uhr schrieb Norman Maurer <
***@***.***>:

**Comment by remmerw** [comment]
Some extra info,

I run quiche QUIC as a client, I have configured the Handler, so that
remote initiated streams should be possible.

ChannelHandler codec = new QuicClientCodecBuilder()
        .sslContext(IPFS.CLIENT_SSL_INSTANCE)
        .maxIdleTimeout(30, TimeUnit.SECONDS)
        .initialMaxData(*10000*)
        .initialMaxStreamDataBidirectionalLocal(10000)
        .initialMaxStreamDataBidirectionalRemote(10000)
        .initialMaxStreamsBidirectional(100)
        .initialMaxStreamsUnidirectional(100)
        .build();


I put a streamHandler on a connection(channel) and my expectation is

that the "remoteAddress" is not an internal streamID. And also

is it working in general, that the remote peer can initiate a stream

to the client, I just set up (somehow it is not working,

maybe I miss something)



 QuicChannel.newBootstrap(codec)

        .streamHandler(new ChannelInboundHandlerAdapter() {
            @Override
            public void channelActive(ChannelHandlerContext ctx)
throws Exception {
                // As we did not allow any remote initiated streams we
will never see this method called.
                // That said just let us keep it here to demonstrate
that this handle would be called
                // for each remote initiated stream.

                LogUtils.error(TAG, "Channel active " + ctx.name());

                QuicStreamChannel quicChannel = (QuicStreamChannel)
ctx.channel();

                LogUtils.error(TAG + "CLIENT", "Remote Address " +
quicChannel.remoteAddress().toString());

                quicChannel.pipeline().addLast(new DataStreamHandler());
            }
        })
        .remoteAddress(new InetSocketAddress(inetAddress, port))
        .connect();



I would be glad for any hint.



Am Mi., 5. Mai 2021 um 16:33 Uhr schrieb Remmer Wilts <
***@***.***>:

**Comment by remmerw** [comment]
Hint: After an update of the source code (for a new try),
there is an issue regarding Android support (if this a goal anyway to support it)

In the class "SockaddrIn" IP4,IP6 addresses are written to a "memory" using
functionality which is not available on an Android system

Example:
PlatformDependent.setMemory(memory, Quiche.SIZEOF_SOCKADDR_IN, (byte) 0);
The PlatformDependent class uses a class "Unsafe" which is not available in Android,
therefore NullPointer exceptions are thrown.

**Comment by normanmaurer** [comment]
The android issue was fixed

**Comment by abezhovets** [comment]
@normanmaurer 
Is it possible to give access to the `remote` field in the `QuicheQuicChannel`? For my project, it would be useful to determine the country of connection.

**Comment by QNENet** [comment]
I am using netty quic in a p2p network.
As Australian NBN connection do not necessarily have fixed IP Addresses it is necessary for destination nodes to advise source nodes if their Ip address has changed and is also necessary for the network discovery process to work.
I have discovered that the InetSocketAddress of the source node is kept in a sender field of netty quic stream and it would be most appreciated if this could be accessed.
