### ISSUE TITLE
I want to know how the server initiated streams?

### ISSUE THREAD

**Issue by Ace931124** [netty/netty-incubator-codec-quic#318]
the server code,etc. 
// ChannelHandler that is added into QuicChannel pipeline.
                .handler(new ChannelInboundHandlerAdapter() {
                    @Override
                    public void channelActive(ChannelHandlerContext ctx) throws InterruptedException {
                        QuicChannel channel = (QuicChannel) ctx.channel();
                        // Create streams etc..
                        QuicStreamChannel streamChannel = channel.createStream(QuicStreamType.BIDIRECTIONAL,
                                new ChannelInboundHandlerAdapter() {
                                    @Override
                                    public void channelRead(ChannelHandlerContext ctx, Object msg) {
                                        ByteBuf byteBuf = (ByteBuf) msg;
                                        System.err.println(byteBuf.toString(CharsetUtil.US_ASCII));
                                        byteBuf.release();
                                    }

                                    @Override
                                    public void userEventTriggered(ChannelHandlerContext ctx, Object evt) {
                                        if (evt == ChannelInputShutdownReadComplete.INSTANCE) {
                                            // Close the connection once the remote peer did send the FIN for this stream.
                                            ((QuicChannel) ctx.channel().parent()).close(true, 0,
                                                    ctx.alloc().directBuffer(16)
                                                            .writeBytes(new byte[]{'k', 't', 'h', 'x', 'b', 'y', 'e'}));
                                        }
                                    }
                                }).sync().getNow();
                    }

when I send the message,I receive an error.
![image](https://user-images.githubusercontent.com/29574611/129011129-a54d8991-3c57-4307-bb6c-d4c357c23c8b.png)

**Comment by NiteshKant** [comment]
Maximum number of streams of each type is bound by [initial transport parameters](https://datatracker.ietf.org/doc/html/rfc9000#section-18.2) and [`MAX_STREAMS`](https://datatracker.ietf.org/doc/html/rfc9000#section-19.11) frames. Additionally these limits are controlled by the peer receiving data on these streams, so in this case you will have to see what are these limits set by the client. 

See the specifications for more details: https://datatracker.ietf.org/doc/html/rfc9000#section-4.6

**Comment by Ace931124** [comment]
Oh,it work.Thank you very much.
