### ISSUE TITLE
What's the best practices to implement keepalvie the channel ?

### ISSUE THREAD

**Issue by Ace931124** [netty/netty-incubator-codec-quic#321]
My design is to use multiple QuicStreamChannels to avoid head-of-line blocking. When the Channel is write idle, I will send keepalive packets, but I can only register a KeepaliveHandler with each QuicStreamChannel, which leads to waste of network traffic.I want to know the best practices.Can you give me some suggestions？ Thank you.

**Comment by NiteshKant** [comment]
I am assuming the keepliave packets mentioned here are [`Quic PING frames`](https://datatracker.ietf.org/doc/html/rfc9000#section-19.2) and you are aware of the [Idle Timeout section](https://datatracker.ietf.org/doc/html/rfc9000#section-10.1) in the spec

> I can only register a KeepaliveHandler with each QuicStreamChannel

You can register handlers on the parent `QuicChannel`, as an example see this:

https://github.com/netty/netty-incubator-codec-quic/blob/main/src/test/java/io/netty/incubator/codec/quic/example/QuicServerExample.java#L67-L86

If you are using `PING` frames, there is no attachment to a specific stream.

**Comment by normanmaurer** [comment]
Unfortunally `quiche` currently does not really expose a way to send a PING frame explicit and will just handle stuff under the hood:

https://github.com/cloudflare/quiche/issues/635

**Comment by NiteshKant** [comment]
Aaah TIL, thanks!

**Comment by Ace931124** [comment]
Currently，I can only use quicStreamChannel to send my custom frame, but the parent channel can't.So, I will wait the quiche support,thanks.

**Comment by oliviercoma** [comment]
Hello @normanmaurer 

Could we re-open this issue as https://github.com/cloudflare/quiche/issues/635 has been implemented?
We need this functionality as well for our project.

Thanks
