### ISSUE TITLE
Is there a performance test report ?

### ISSUE THREAD

**Issue by Ace931124** [netty/netty-incubator-codec-quic#326]
Is there a performance test report, Thanks.

**Comment by Ace931124** [comment]
I use jmeter to test the performance,and I found that when the network drop rate at 2%,the performance is highest.But I don't know the reason.Can you get some suggestions ? Thanks

**Comment by Ace931124** [comment]
Oh, I test the througthput.

**Comment by normanmaurer** [comment]
There is nothing at the moment. I did test the performance before by writing my own client / server
