### ISSUE TITLE
How to decrypt QUIC packet with wireshark？

### ISSUE THREAD

**Issue by lostk1ng** [netty/netty-incubator-codec-quic#333]
I am running QuicClientExample/QuicServerExample, and want to analyse the QUIC packet. Is there a way to decrypt QUIC packet using wireshark?

**Comment by normanmaurer** [comment]
not at the moment

**Comment by hyperxpro** [comment]
Try using `PcapWriteHandler`. Wireshark supports QUIC if it's decrypted. Though, I am not sure how to insert `PcapWriteHandler` into `QuicChannel`. @normanmaurer Am I missing something?

**Comment by lostk1ng** [comment]
Supported by https://github.com/netty/netty-incubator-codec-quic/pull/343
