### ISSUE TITLE
0-RTT supported ？

### ISSUE THREAD

**Issue by wenlongkang** [netty/netty-incubator-codec-quic#337]
Hi，I did not find the relevant code, Is 0-RTT supported now?

**Comment by lostk1ng** [comment]
I am currently investigate how to support 0RTT on client side and found some works already be done [here](https://github.com/cloudflare/quiche/pull/919) . But when I try to call the `quiche_conn_session` function via JNI to get ssl session, it returns null which seems does not work.

By looking into the [quiche source code](https://github.com/cloudflare/quiche/pull/911/files#diff-f229bc4b874c8edcd2c19a11fe9871e47d51519cf51ed829058f0bdbb1e4b27b) , it use BoringSSL API `void SSL_CTX_sess_set_new_cb(SSL_CTX *ctx, int (*new_session_cb)(SSL *ssl, SSL_SESSION *session))` which a callback should be registered on SSL_CTX to get ssl session. 

However, our project build SSL_CTX outside quiche, so we should support session resumption/0RTT via BoringSSL API other than quiche C API?  Can you confirm this ?  @normanmaurer

**Comment by normanmaurer** [comment]
Server support was added in https://github.com/netty/netty-incubator-codec-quic/pull/356.

**Comment by normanmaurer** [comment]
@lostk1ng will have a look

**Comment by normanmaurer** [comment]
@lostk1ng yes... I think we need to port over this:

https://github.com/netty/netty/commit/7d4aaa268b8a536f61fbc7711365147c58238745#diff-d92a33e50c3e6fc003999ef8be7441f18b35cb0e36b295e0ef685e0b5f860da8

Makes sense ?

**Comment by lostk1ng** [comment]
@normanmaurer Thanks, I will look into it later.

**Comment by normanmaurer** [comment]
@lostk1ng cool... Let me know if you need any help. BTW what do you use QUIC for ?

**Comment by lostk1ng** [comment]
@normanmaurer Thanks, I will open a pr to support 0RTT on client side which really depends on my working progress, I think  we can discuss it when the pr is ready.

Our IM gateway server is powered by netty using TCP, now we are trying to make some experiment on changing TCP to QUIC as QUIC IETF v1 is officially released this year.

**Comment by normanmaurer** [comment]
> @normanmaurer Thanks, I will open a pr to support 0RTT on client side which really depends on my working progress, I think  we can discuss it when the pr is ready.
> 
> 
> 
> Our IM gateway server is powered by netty using TCP, now we are trying to make some experiment on changing TCP to QUIC as QUIC IETF v1 is officially released this year.

Is it oss by any chance ?

**Comment by lostk1ng** [comment]
> > @normanmaurer Thanks, I will open a pr to support 0RTT on client side which really depends on my working progress, I think  we can discuss it when the pr is ready.
> > Our IM gateway server is powered by netty using TCP, now we are trying to make some experiment on changing TCP to QUIC as QUIC IETF v1 is officially released this year.
> 
> Is it oss by any chance ?

Nope. It is a project inside our [company](https://en.wikipedia.org/wiki/Sina_Weibo) and it is not open sourced.

**Comment by normanmaurer** [comment]
@lostk1ng you already started with this ? If not I might pick it up

**Comment by lostk1ng** [comment]
@normanmaurer I have to prepare a presentation and have no more time recently , so it is no complete yet. I have done some simple work, and will start a pr tomorrow, can you help to finish it?

**Comment by normanmaurer** [comment]
client side was merged as well which means all is in place now: 

https://github.com/netty/netty-incubator-codec-quic/pull/362

**Comment by normanmaurer** [comment]
> > > @normanmaurer Thanks, I will open a pr to support 0RTT on client side which really depends on my working progress, I think  we can discuss it when the pr is ready.
> > > Our IM gateway server is powered by netty using TCP, now we are trying to make some experiment on changing TCP to QUIC as QUIC IETF v1 is officially released this year.
> > 
> > 
> > Is it oss by any chance ?
> 
> Nope. It is a project inside our [company](https://en.wikipedia.org/wiki/Sina_Weibo) and it is not open sourced.

Would be cool to have you listed here:

https://github.com/netty/netty/wiki/Adopters

**Comment by lostk1ng** [comment]
@normanmaurer Added!
