### ISSUE TITLE
Netty QUIC Codec versions 0.0.21.Final and 0.0.22.Final for windows are not available on Maven Central

### ISSUE THREAD

**Issue by violetagg** [netty/netty-incubator-codec-quic#361]
I cannot find `Netty QUIC Codec` versions `0.0.21.Final` and `0.0.22.Final` on Maven Central. Is that intentional?

**Comment by normanmaurer** [comment]
@violetagg you might have missed that the artifactId changed: https://netty.io/news/2021/11/12/quic-0-0-21-Final.html

**Comment by violetagg** [comment]
@normanmaurer I've missed that change. Thanks a lot.

**Comment by normanmaurer** [comment]
Hmm if that's the case it's a problem with the release process... let me check

**Comment by normanmaurer** [comment]
Released 0.0.23.Final which now also includes windows again https://repo1.maven.org/maven2/io/netty/incubator/netty-incubator-codec-native-quic/0.0.23.Final/

**Comment by violetagg** [comment]
@normanmaurer Thanks a lot
