### ISSUE TITLE
Consider adding multi-arch uber deployable

### ISSUE THREAD

**Issue by juddgaddie** [netty/netty-incubator-codec-quic#363]
When this is no longer experimental, having a uber jar that includes the binaries for all supported platforms and then selects the appropriate one, significantly simpliifies deployment.

Similar to 
```
netty-tcnative-boringssl-static 
This is an uber jar that contains the statically linked libraries for all supported netty-tcnative-boringssl-static-{os_arch}. While this tends to be a fairly large jar, it greatly simplifies the getting started experience since an application need not be concerned with obtaining the correct jar for the platform.
```

**Comment by normanmaurer** [comment]
@juddgaddie what is the problem with just including all of the different artifacts with the classifiers directly ?
