### ISSUE TITLE
SslContext is compulssory

### ISSUE THREAD

**Issue by zipper01** [netty/netty-incubator-codec-quic#377]
Without `.sslContext(context)` the `new QuicClientCodecBuilder()` hangs. My app data is already encrypted I don't want the SSL encryption. (another case the UDP carrier layer may be in IPSEC turnnel?)

        <dependency>
            <groupId>io.netty.incubator</groupId>
            <artifactId>netty-incubator-codec-native-quic</artifactId>
            <version>0.0.24.Final</version>
            <classifier>windows-x86_64</classifier>
        </dependency>

**Comment by normanmaurer** [comment]
@zipper01 we currently don't support QUIC without TLSv1.3. That said I think wee should at least throw an exception in this case to fail hard.

**Comment by normanmaurer** [comment]
Actually we should already throw if `sslContext(...)` / `sslEngineProvider(...)` was not called and you calll `build()`. Is this not the case for you ?

**Comment by zipper01** [comment]
Thank you. Exception was thrown. I think this is because ssl is enforced by quiche?

**Comment by normanmaurer** [comment]
Yes
