### ISSUE TITLE
`A fatal error has been detected by the Java Runtime Environment` when transfering large data

### ISSUE THREAD

**Issue by zipper01** [netty/netty-incubator-codec-quic#379]
I was trying to use quic for relaying data between two relay agents, small data is OK, but large data got the Java fatal error. 
$ ls -tl
-rw-r--r-- 1 root root  6080108 Jan 16 22:02 log.txt20220116220259.bak
$ cat log.txt20220116220259.bak //<----relaying the `cat` output causes problem at the sending side.

log file:
[hs_err_pid16792.log](https://github.com/netty/netty-incubator-codec-quic/files/7890472/hs_err_pid16792.log)

**Comment by zipper01** [comment]
It seems this is caused by `EmbeddedChannel.writeInbound` not the quic codec -- I'm trying to use EmbeddedChannel as carriers of quicChannels other than using the udpChannel directly, because I want to use the same udp port for connecting as a client for connecting to the Web Server and listening as a server for P2P connection, by prepend a header for duplexing. I searched and [this link](https://forums.minecraftforge.net/topic/26669-1710-fatal-error/) shows a similar unsolving problem of using `EmbeddedChannel.writeInbound`.

**Comment by normanmaurer** [comment]
Do you have a reproducer I can run ?

**Comment by zipper01** [comment]
@normanmaurer  -- Thank you for the patience sir. I made some changes trying to fix and the "fatal error" is gone, need to dig more to reproduce the exact problem. But now the problems are:

1). The no-EmbeddedChannel version (QuicClientExample1 bellow) is OK, but at server side the size of the received file is smaller than the sent file and the size delta is at random.

2). Using EmbeddedChannel (QuicClientExample2 bellow) as the carrier channel as previously described hangs when sending a large file;

Test file at sending side:
-a----        11/29/2020   5:15 PM      148561662 testVideo.mp4

Received files of different runs:
-rw-r--r-- 1 root root 148030677 Jan 23 22:05 testVideo.mp4.bak4
-rw-r--r-- 1 root root 148051809 Jan 23 21:58 testVideo.mp4.bak3
-rw-r--r-- 1 root root 148322281 Jan 23 21:53 testVideo.mp4.bak2
-rw-r--r-- 1 root root 147399313 Jan 23 21:48 testVideo.mp4.bak

Bellow reproducer codes are derived from [the example of THIS project](https://github.com/netty/netty-incubator-codec-quic/tree/main/codec-native-quic/src/test/java/io/netty/incubator/codec/quic).

`1. Demo code for the Server, receiving a file and write to disk:

    package com.mycompany.quicserverexample;
    import io.netty.bootstrap.Bootstrap;
    import io.netty.buffer.ByteBuf;
    import io.netty.channel.Channel;
    import io.netty.channel.ChannelHandler;
    import io.netty.channel.ChannelHandlerContext;
    import io.netty.channel.ChannelInboundHandlerAdapter;
    import io.netty.channel.ChannelInitializer;
    import io.netty.channel.SimpleChannelInboundHandler;
    import io.netty.channel.nio.NioEventLoopGroup;
    import io.netty.channel.socket.nio.NioDatagramChannel;
    import io.netty.incubator.codec.quic.InsecureQuicTokenHandler;
    import io.netty.incubator.codec.quic.QuicChannel;
    import io.netty.incubator.codec.quic.QuicServerCodecBuilder;
    import io.netty.incubator.codec.quic.QuicSslContext;
    import io.netty.incubator.codec.quic.QuicSslContextBuilder;
    import io.netty.incubator.codec.quic.QuicStreamChannel;
    import io.netty.util.CharsetUtil;
    import io.netty.util.internal.logging.InternalLogger;
    import io.netty.util.internal.logging.InternalLoggerFactory;
    import java.io.File;
    import java.io.FileNotFoundException;
    import java.io.FileOutputStream;
    import java.io.IOException;
    
    import java.net.InetSocketAddress;
    
    import java.util.concurrent.TimeUnit;
    
    public final class QuicServerExample {
    
        private static final InternalLogger LOGGER = InternalLoggerFactory.getInstance(QuicServerExample.class);
    
        private QuicServerExample() {
        }
    
        public static void main(String[] args) throws Exception {
            if (args.length < 1) {
                System.exit(-1);
            }
            File keyFile = new File("/root/dev/test/cert.pk8");
            File certFile = new File("/root/dev/test/cert.crt");
            QuicSslContext context = QuicSslContextBuilder.forServer(keyFile, null, certFile)
                    .applicationProtocols("http/0.9").build();
            NioEventLoopGroup group = new NioEventLoopGroup(1);
            ChannelHandler codec = new QuicServerCodecBuilder()
                    .sslContext(context)
                    .maxIdleTimeout(5000, TimeUnit.MILLISECONDS)
                    .initialMaxData(10000000)
                    .initialMaxStreamDataBidirectionalLocal(1000000)
                    .initialMaxStreamDataBidirectionalRemote(1000000)
                    .initialMaxStreamsBidirectional(100)
                    .initialMaxStreamsUnidirectional(100)
                    .tokenHandler(InsecureQuicTokenHandler.INSTANCE)
                    .handler(new ChannelInboundHandlerAdapter() {
                        @Override
                        public void channelActive(ChannelHandlerContext ctx) {
                            QuicChannel quicCh = (QuicChannel) ctx.channel();
                            System.out.println("channelActive");
                            // Create streams etc.
                        }
    
                        @Override
                        public void channelInactive(ChannelHandlerContext ctx) {
                            ((QuicChannel) ctx.channel()).collectStats().addListener(f -> {
                                if (f.isSuccess()) {
                                    LOGGER.info("Connection closed: ", f.getNow());
                                }
                            });
                        }
    
                        @Override
                        public boolean isSharable() {
                            return true;
                        }
                    })
                    .streamHandler(new ChannelInitializer<QuicStreamChannel>() {
                        @Override
                        protected void initChannel(QuicStreamChannel streamCh) {
                            streamCh.pipeline().addLast(new SimpleChannelInboundHandler() {
                                int nReads = 0;
                                int nBytesReceived = 0;
                                FileOutputStream os = null;
    
                                @Override
                                public void channelRead0(ChannelHandlerContext ctx, Object msg)
                                        throws FileNotFoundException, IOException {
                                    ByteBuf buf = (ByteBuf) msg;
                                    if (nReads++ == 0) {
                                        String fname = buf.toString(CharsetUtil.US_ASCII);
                                        os = new FileOutputStream(fname);
                                        System.out.println("write file: " + fname);
                                    } else {
                                        byte[] bytes = new byte[buf.readableBytes()];
                                        buf.readBytes(bytes);
                                        os.write(bytes);
                                        nBytesReceived += bytes.length;
                                        System.out.println(bytes.length + " bytes received, total = " + nBytesReceived);
                                    }
                                }
    
                                @Override
                                public void channelInactive(ChannelHandlerContext ctx) throws IOException {
                                    System.out.println(nBytesReceived + " bytes written.");
                                    os.close();
                                    streamCh.close();
                                }
                            });
                        }
                    }).build();
            try {
                Bootstrap bs = new Bootstrap();
                Channel udpCh = bs.group(group)
                        .channel(NioDatagramChannel.class)
                        .handler(codec)
                        .bind(new InetSocketAddress(new Integer(args[0]))).sync().channel();
                udpCh.closeFuture().sync();
            } finally {
                group.shutdownGracefully();
            }
        }
    }
`
`2. Demo code for the client, sending a file to the server over QUIC connection. This one can send normally, but the received files are randomly smaller than the sent file at the server side, as depicted above.

    package com.mycompany.quicclientexample1;
    import io.netty.bootstrap.Bootstrap;
    import io.netty.buffer.ByteBuf;
    import io.netty.buffer.Unpooled;
    import io.netty.channel.Channel;
    import io.netty.channel.ChannelHandler;
    import io.netty.channel.ChannelHandlerContext;
    import io.netty.channel.ChannelInboundHandlerAdapter;
    import io.netty.channel.nio.NioEventLoopGroup;
    import io.netty.channel.socket.ChannelInputShutdownReadComplete;
    import io.netty.channel.socket.nio.NioDatagramChannel;
    import io.netty.handler.ssl.util.InsecureTrustManagerFactory;
    import io.netty.incubator.codec.quic.QuicChannel;
    import io.netty.incubator.codec.quic.QuicClientCodecBuilder;
    import io.netty.incubator.codec.quic.QuicSslContext;
    import io.netty.incubator.codec.quic.QuicSslContextBuilder;
    import io.netty.incubator.codec.quic.QuicStreamChannel;
    import io.netty.incubator.codec.quic.QuicStreamType;
    import io.netty.util.CharsetUtil;
    import io.netty.util.concurrent.Promise;
    import java.io.FileInputStream;
    import java.io.IOException;
    
    import java.net.InetSocketAddress;
    import java.util.concurrent.TimeUnit;
    
    public class QuicClientExample1 {
    
        public static volatile int nBytesSent = 0;
        public static volatile int nBytesRead = 0;
    
        public static void main(String[] args) throws Exception {
            if (args.length < 2) {
                System.exit(-1);
            }
            NioEventLoopGroup group = new NioEventLoopGroup(1);
            QuicSslContext context = QuicSslContextBuilder.forClient()
                    .trustManager(InsecureTrustManagerFactory.INSTANCE)
                    .applicationProtocols("http/0.9").build();
            ChannelHandler codec = new QuicClientCodecBuilder()
                    .sslContext(context)
                    .maxIdleTimeout(5000, TimeUnit.MILLISECONDS)
                    .initialMaxData(10000000)
                    .initialMaxStreamDataBidirectionalLocal(1000000)
                    .build();
            Bootstrap bs = new Bootstrap();
            Channel udpCh = bs.group(group)
                    .channel(NioDatagramChannel.class)
                    .handler(codec)
                    .bind(0).sync().channel();
    
            try {
                QuicChannel.newBootstrap(udpCh)
                        .streamHandler(new ChannelInboundHandlerAdapter() {
                            @Override
                            public void channelActive(ChannelHandlerContext ctx) {
                                //ctx.close();
                            }
                        }).remoteAddress(new InetSocketAddress(args[0], new Integer(args[1])))
                        .connect().addListener(f -> {
                            if (f.isSuccess()) {
                                QuicChannel quicCh = ((Promise<QuicChannel>) f).get();
                                QuicStreamChannel streamCh = quicCh.createStream(QuicStreamType.BIDIRECTIONAL,
                                        new ChannelInboundHandlerAdapter() {
                                    @Override
                                    public void channelRead(ChannelHandlerContext ctx, Object msg) {
                                        ByteBuf buf = (ByteBuf) msg;
                                        String str = buf.toString(CharsetUtil.US_ASCII);
                                        System.out.print(str);
                                        ctx.writeAndFlush(msg).addListener(f -> {
                                            //
                                        });
                                    }
    
                                    @Override
                                    public void userEventTriggered(ChannelHandlerContext ctx, Object evt) {
                                        if (evt == ChannelInputShutdownReadComplete.INSTANCE) {
                                            ((QuicChannel) ctx.channel().parent()).close(true, 0,
                                                    ctx.alloc().directBuffer(16)
                                                            .writeBytes(new byte[]{'k', 't', 'h', 'x', 'b', 'y', 'e'}));
                                        }
                                    }
                                }).sync().getNow();
    
                                new Thread() {
                                    @Override
                                    public void run() {
                                        streamCh.writeAndFlush(Unpooled.wrappedBuffer("testVideo.mp4".getBytes()));
                                        try ( FileInputStream is = new FileInputStream("d:\\zg\\dev\\test\\testVideo.mp4")) {
                                            for (;;) {
                                                byte[] bytes = new byte[65535];
                                                int n = is.read(bytes, 0, bytes.length);
                                                if (n > 0) {
                                                    nBytesRead += n;
                                                    streamCh.writeAndFlush(Unpooled.wrappedBuffer(bytes, 0, n))
                                                            .addListener(f -> {
                                                                if (f.isSuccess()) {
                                                                    nBytesSent += n;
                                                                    System.out.println(n + " bytes sent, total = " + nBytesSent);
                                                                    if (nBytesSent >= nBytesRead) {
                                                                        System.out.println("finished sending, exit. ");
                                                                        streamCh.close();
                                                                        udpCh.close();
                                                                    }
                                                                } else {
                                                                    System.out.println("error sending, exit");
                                                                    is.close();
                                                                    udpCh.close();
                                                                }
                                                            });
                                                } else if (n == -1) {
                                                    System.out.println("end of file.");
                                                    is.close();
                                                    break;
                                                }
                                            }
                                        } catch (IOException ex) {
                                            ex.printStackTrace(System.err);
                                        }
                                    }
                                }.start();
    
                            } else {
                                System.err.println("connection failed!");
                                System.exit(-1);
                            }
                        });
            } finally {
                udpCh.closeFuture().sync();
                group.shutdownGracefully();
            }
        }
    }
`
`3. Demo code for the client, sending a file to the server over QUIC connection. I used a EmbeddedChannel as the carrier of the quicCh other than using the udpCh to carrier the quicCh directly This one hung during sending.

    package com.mycompany.quicclientexample2;
    import io.netty.bootstrap.Bootstrap;
    import io.netty.buffer.ByteBuf;
    import io.netty.buffer.Unpooled;
    import io.netty.channel.Channel;
    import io.netty.channel.ChannelHandler;
    import io.netty.channel.ChannelHandlerContext;
    import io.netty.channel.ChannelInboundHandlerAdapter;
    import io.netty.channel.ChannelOutboundHandlerAdapter;
    import io.netty.channel.ChannelPromise;
    import io.netty.channel.embedded.EmbeddedChannel;
    import io.netty.channel.nio.NioEventLoopGroup;
    import io.netty.channel.socket.ChannelInputShutdownReadComplete;
    import io.netty.channel.socket.nio.NioDatagramChannel;
    import io.netty.handler.ssl.util.InsecureTrustManagerFactory;
    import io.netty.incubator.codec.quic.QuicChannel;
    import io.netty.incubator.codec.quic.QuicClientCodecBuilder;
    import io.netty.incubator.codec.quic.QuicSslContext;
    import io.netty.incubator.codec.quic.QuicSslContextBuilder;
    import io.netty.incubator.codec.quic.QuicStreamChannel;
    import io.netty.incubator.codec.quic.QuicStreamType;
    import io.netty.util.CharsetUtil;
    import io.netty.util.concurrent.Promise;
    import java.io.FileInputStream;
    import java.io.IOException;
    
    import java.net.InetSocketAddress;
    import java.util.concurrent.TimeUnit;
    import java.util.function.BiConsumer;
    
    public class QuicClientExample2 {
    
        /**
         * Multiplex the RS QUIC connection and P2P QUIC connections to the same UDP
         * port. Each QUIC connection is carried by a EmbeddedChannel instance.
         */
        private static class MuxChannelInboundHandlerAdapter extends ChannelInboundHandlerAdapter {
    
            private BiConsumer<ChannelHandlerContext, Object> taskForChannelRead = null;
    
            @Override
            public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
                if (taskForChannelRead != null) {
                    taskForChannelRead.accept(ctx, msg);
                } else {
                    ctx.fireChannelRead(msg);
                }
            }
        }
    
        public static volatile int nBytesSent = 0;
        public static volatile int nBytesRead = 0;
    
        public static void main(String[] args) throws Exception {
            if (args.length < 2) {
                System.exit(-1);
            }
            MuxChannelInboundHandlerAdapter muxInboundHandler = new MuxChannelInboundHandlerAdapter();
            NioEventLoopGroup group = new NioEventLoopGroup(1);
            Bootstrap bs = new Bootstrap();
            Channel udpCh = bs.group(group)
                    .channel(NioDatagramChannel.class)
                    .handler(muxInboundHandler)
                    .bind(0).sync().channel();
    
            ChannelOutboundHandlerAdapter muxOutboundHandler = new ChannelOutboundHandlerAdapter() {
                @Override
                public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
                    udpCh.write(msg);
                }
    
                @Override
                public void flush(ChannelHandlerContext ctx) throws Exception {
                    udpCh.flush();
                }
            };
    
            QuicSslContext context = QuicSslContextBuilder.forClient()
                    .trustManager(InsecureTrustManagerFactory.INSTANCE)
                    .applicationProtocols("http/0.9").build();
            ChannelHandler codec = new QuicClientCodecBuilder()
                    .sslContext(context)
                    .maxIdleTimeout(5000, TimeUnit.MILLISECONDS)
                    .initialMaxData(10000000)
                    .initialMaxStreamDataBidirectionalLocal(1000000)
                    .build();
            EmbeddedChannel clientCarrierCh = new EmbeddedChannel(muxOutboundHandler, codec);
            muxInboundHandler.taskForChannelRead = (ctx, msg) -> {
                clientCarrierCh.writeInbound(msg);
            };
    
            try {
                QuicChannel.newBootstrap(clientCarrierCh)
                        .streamHandler(new ChannelInboundHandlerAdapter() {
                            @Override
                            public void channelActive(ChannelHandlerContext ctx) {
                                //ctx.close();
                            }
                        }).remoteAddress(new InetSocketAddress(args[0], new Integer(args[1])))
                        .connect().addListener(f -> {
                            if (f.isSuccess()) {
                                QuicChannel quicCh = ((Promise<QuicChannel>) f).get();
                                QuicStreamChannel streamCh = quicCh.createStream(QuicStreamType.BIDIRECTIONAL,
                                        new ChannelInboundHandlerAdapter() {
                                    @Override
                                    public void channelRead(ChannelHandlerContext ctx, Object msg) {
                                        ByteBuf buf = (ByteBuf) msg;
                                        String str = buf.toString(CharsetUtil.US_ASCII);
                                        System.out.print(str);
                                        ctx.writeAndFlush(msg).addListener(f -> {
                                            //
                                        });
                                    }
    
                                    @Override
                                    public void userEventTriggered(ChannelHandlerContext ctx, Object evt) {
                                        if (evt == ChannelInputShutdownReadComplete.INSTANCE) {
                                            ((QuicChannel) ctx.channel().parent()).close(true, 0,
                                                    ctx.alloc().directBuffer(16)
                                                            .writeBytes(new byte[]{'k', 't', 'h', 'x', 'b', 'y', 'e'}));
                                        }
                                    }
                                }).sync().getNow();
    
                                new Thread() {
                                    @Override
                                    public void run() {
                                        streamCh.writeAndFlush(Unpooled.wrappedBuffer("testVideo.mp4".getBytes()));
                                        try ( FileInputStream is = new FileInputStream("d:\\zg\\dev\\test\\testVideo.mp4")) {
                                            for (;;) {
                                                byte[] bytes = new byte[65535];
                                                int n = is.read(bytes, 0, bytes.length);
                                                if (n > 0) {
                                                    nBytesRead += n;
                                                    streamCh.writeAndFlush(Unpooled.wrappedBuffer(bytes, 0, n))
                                                            .addListener(f -> {
                                                                if (f.isSuccess()) {
                                                                    nBytesSent += n;
                                                                    System.out.println(n + " bytes sent, total = " + nBytesSent);
                                                                    if (nBytesSent >= nBytesRead) {
                                                                        System.out.println("finished sending, exit. ");
                                                                        streamCh.close();
                                                                        udpCh.close();
                                                                    }
                                                                } else {
                                                                    System.out.println("error sending, exit");
                                                                    is.close();
                                                                    streamCh.close();
                                                                    udpCh.close();
                                                                }
                                                            });
                                                } else if (n == -1) {
                                                    System.out.println("end of file.");
                                                    is.close();
                                                    break;
                                                }
                                            }
                                        } catch (IOException ex) {
                                            ex.printStackTrace(System.err);
                                        }
                                    }
                                }.start();
    
                            } else {
                                System.err.println("connection failed!");
                                System.exit(-1);
                            }
                        });
            } finally {
                udpCh.closeFuture().sync();
                group.shutdownGracefully();
            }
        }
    }
`

**Comment by zipper01** [comment]
After some study and try, point 2) is solved by setting `QuicChannelOption.READ_FRAMES` to `true` for the streamChannel at both side; calling `shutdownOutput()` to send FIN/RESET_STREAM from the sender; calling the same to acknowledge it after receiving the FIN. 

Suggest to have add a boolean argument for `QuicStreamChannel.close()` and default to true to run this handshake automatically;

Point 1) remains to be a problem.

**Comment by zipper01** [comment]
It seems this quic lib tightly binds to the udp carring channel for flow control when sending. I tried to use `isWritable()` and `channelWritabilityChanged` to control the writing speed but the connect was still broken after a while, in the case that the embededChannel mux layer sits at the middle of the udp channel and the quic channel (QuicClientExample2). I don't know if there is a convenient way to mux.

**Comment by zipper01** [comment]
Close as this is not a bug.
