### ISSUE TITLE
Use Quiche debug logging

### ISSUE THREAD

**Issue by thomdev** [netty/netty-incubator-codec-quic#4]
Quiche can produce debug logging (using `quiche_enable_debug_logging()`) that show incoming and outgoing QUIC frames. It would be nice to expose it to Java. Even though the logging handler is global, we should be able to use thread-local variables to control logging per QUIC connection, and show the underlying channel on each log line.

**Comment by normanmaurer** [comment]
@thomdev I did merge a fix for this... I did just ensure the `QuicheQuicChannel` is using the same `trace_id` in its `ChannelId` as quiche so you can match up the channel to the quiche log. This is cheaper and less ugly.
