### ISSUE TITLE
Browser cannot access test example address

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty-incubator-codec-quic#404]
The browser cannot be accessed, but it can be determined that the browser supports http3

**Comment by heixiaoma** [comment]
https://github.com/netty/netty-incubator-codec-http3/blob/main/src/test/java/io/netty/incubator/codec/http3/example/Http3ServerExample.java

**Comment by silence934** [comment]
I have the same question

**Comment by heixiaoma** [comment]
With the latest version of curl, you can access

curl " https://127.0.0.1:9999/ " --http3 -I

**Comment by silence934** [comment]
我也成功了 但是还是非常想通过浏览器访问，我在谷歌浏览器启动的时候，强制让浏览器使用quic访问我的服务，通过日志我可以看到浏览器与我的服务建立了链接，并且发送了数据，但是浏览器页面是这样的
![image](https://user-images.githubusercontent.com/49453669/184788675-54aff052-23e9-41d6-b676-2e661c2e2ef1.png)

**Comment by normanmaurer** [comment]
Works for me..
