### ISSUE TITLE
Method get() happened exception

### ISSUE THREAD

**Issue by dongdong2980** [netty/netty-incubator-codec-quic#405]
when i run example:QuicClientExample.java, "get()",  there is exception,

`            QuicChannel quicChannel = QuicChannel.newBootstrap(channel)
                    .streamHandler(new ChannelInboundHandlerAdapter() {
                        @Override
                        public void channelActive(ChannelHandlerContext ctx) {
                            // As we did not allow any remote initiated streams we will never see this method called.
                            // That said just let us keep it here to demonstrate that this handle would be called
                            // for each remote initiated stream.
                            ctx.close();
                        }
                    })
                    .remoteAddress(new InetSocketAddress(host, port))
                    .connect()
                    .get();`

exception:
`java.util.concurrent.ExecutionException: io.netty.channel.ConnectTimeoutException: connection timed out: QuicConnectionAddress{EPHEMERAL}
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41)`

I use "nc.exe", the ip and port are open.

**Comment by normanmaurer** [comment]
I am working on a fix... stay tuned

**Comment by normanmaurer** [comment]
I think it should be fixed.. Please reopen with more details if its still happens
