### ISSUE TITLE
The QuicStreamChannel cannot be closed gracefully.

### ISSUE THREAD

**Issue by vovgou** [netty/netty-incubator-codec-quic#416]
hi

When calling the close function of QuicStreamChannel on the client side, the client stream channel is closed normally, but the server stream channel will not be closed.

When calling the shutdown function of  QuicStreamChannel on the client side, the client stream channel will not be closed, but the server side stream channel can be closed.

        QuicSslContext context = QuicSslContextBuilder.forClient()
					.trustManager(InsecureTrustManagerFactory.INSTANCE).applicationProtocols("http/0.9").build();
			NioEventLoopGroup group = new NioEventLoopGroup(1);
			try {
				ChannelHandler codec = new QuicClientCodecBuilder().sslContext(context)
                                                //.maxIdleTimeout(10000, TimeUnit.MILLISECONDS)
						.initialMaxData(10000000)
						.initialMaxStreamDataBidirectionalLocal(1000000).build();

				Bootstrap bs = new Bootstrap();
				Channel channel = bs.group(group).channel(NioDatagramChannel.class).handler(codec).bind(0).sync()
						.channel();

				QuicChannel quicChannel = QuicChannel.newBootstrap(channel)
						.streamHandler(new ChannelInboundHandlerAdapter() {
							@Override
							public void channelActive(ChannelHandlerContext ctx) {
								ctx.close();
							}
						}).remoteAddress(new InetSocketAddress(NetUtil.LOCALHOST4, 9999)).connect().get();

				QuicStreamChannel streamChannel = quicChannel
						.createStream(QuicStreamType.BIDIRECTIONAL, new ChannelInboundHandlerAdapter() {
							@Override
							public void channelRead(ChannelHandlerContext ctx, Object msg) {
								ByteBuf byteBuf = (ByteBuf) msg;
								System.out.println(byteBuf.toString(CharsetUtil.US_ASCII));
								byteBuf.release();
							}

							@Override
							public void userEventTriggered(ChannelHandlerContext ctx, Object evt) {
								System.out.println(ctx.channel() + " userEventTriggered:" + evt);
							}
						}).sync().getNow();

				 streamChannel.writeAndFlush(Unpooled.copiedBuffer("GET /\r\n",CharsetUtil.US_ASCII));

				streamChannel.closeFuture().addListener(f -> System.out.println("closed channel:" + streamChannel));

  				//streamChannel.shutdown()
  				//		.addListener(f -> System.out.println("shutdown channel:" + streamChannel + " isInputShutdown:"
  				//				+ streamChannel.isInputShutdown() + " isOutputShutdown:"
  				//				+ streamChannel.isOutputShutdown()));

				streamChannel.close()
						.addListener(f -> System.out.println(
								"close channel:" + streamChannel + " isInputShutdown:" + streamChannel.isInputShutdown()
										+ " isOutputShutdown:" + streamChannel.isOutputShutdown()));

				streamChannel.closeFuture().sync();
				quicChannel.closeFuture().sync();
				channel.close().sync();
			} finally {
				group.shutdownGracefully();
			}

**Comment by normanmaurer** [comment]
We have tests in `QuicStreamHalfClosureTest` and all works as expected
