### ISSUE TITLE
通过谷歌浏览器访问ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by silence934** [netty/netty-incubator-codec-quic#420]
The official SSL certificate is used.
I can do this with curl
<img width="363" alt="image" src="https://user-images.githubusercontent.com/49453669/183041484-2239fa37-4550-4373-baa4-7093929c3993.png">
I used the parameter to force Google Chrome to use Quic to access the service:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/49453669/183041745-971e55f3-81a8-40d4-b90a-c7b0e29ba90f.png">

This is the problem:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/49453669/183041846-de2b9b97-ee0f-4b1a-ab3c-be0f9f1730c4.png">

**Comment by silence934** [comment]
Sorry, the screenshot is wrong
<img width="820" alt="image" src="https://user-images.githubusercontent.com/49453669/183043007-d5c135be-cbbf-4ca3-ad73-65973dfcb124.png">

**Comment by silence934** [comment]
ERR_QUIC_PROTOCOL_ERROR，I can't get any more information than that。
I can confirm that my response message was sent

![Uploading image.png…]()

**Comment by heixiaoma** [comment]
我也是遇到同样的问题

**Comment by silence934** [comment]
> 我也是遇到同样的问题

有排查方向嘛

**Comment by heixiaoma** [comment]
目前还没有，感觉需要像http2一样协商升级一样，网上也有用http3的网站，但是都是先走http2协议访问的最后才升级到http3的，你可以观察下，首次访问都是http2 最后才是http3

**Comment by silence934** [comment]
> 目前还没有，感觉需要像http2一样协商升级一样，网上也有用http3的网站，但是都是先走http2协议访问的最后才升级到http3的，你可以观察下，首次访问都是http2 最后才是http3

谷歌浏览器使用  --origin-to-force-quic-on  参数可以强制使用quic访问服务，我使用后的确是这样的，服务日志现实数据交互一切正常，只是浏览器显示ERR QUIC PROTOCOL ERROR

**Comment by heixiaoma** [comment]
😂只有在看看，有时间在研究下，当时也是测试下

**Comment by silence934** [comment]
> 😂只有在看看，有时间在研究下，当时也是测试下

我已经可以在chroem中使用http3访问了，这是我的项目地址: [http3](https://github.com/silence934/http3  )

**Comment by normanmaurer** [comment]
Please use English ...
