### ISSUE TITLE
What's the benefit to use QUIC in netty?

### ISSUE THREAD

**Issue by Jeffwan** [netty/netty-incubator-codec-quic#422]
Can someone help explain the user scenario of QUIC in netty and what's the benefit we expect?

**Comment by hyperxpro** [comment]
User Scenario: To use QUIC for their workload
Benefit: QUIC available in Netty for Java

**Comment by daschl** [comment]
@Jeffwan also it is going to be essential for good HTTP/3 support.

**Comment by normanmaurer** [comment]
Yep QUIC is needed for HTTP/3.
