### ISSUE TITLE
Zero copy support

### ISSUE THREAD

**Issue by silence934** [netty/netty-incubator-codec-quic#425]
Is there any support for zero copy?
thank you

**Comment by normanmaurer** [comment]
What exactly you want to "zero copy" ?

**Comment by silence934** [comment]
> What exactly you want to "zero copy" ?

Send  local file

**Comment by normanmaurer** [comment]
@silence934 there cant be zero copy as it needs to be encrypted.

**Comment by silence934** [comment]
> @silence934不能有零拷贝，因为它需要加密。

ok  ，i know
