### ISSUE TITLE
Sometimes quickSreamChannel isWritable will always return false

### ISSUE THREAD

**Issue by zhining-lu** [netty/netty-incubator-codec-quic#454]
I use it to implement echo service, when I use multiple streams on a quic channel to send data for a long time, sometimes quickSreamChannel isWritable will return false on the server side, and it will not become true. I found that streams capability=0, so this problem should be a bug in quiche.

**Comment by normanmaurer** [comment]
Please provide a reproducer

**Comment by zhining-lu** [comment]
I'm trying to make it easier to reproduce

**Comment by zhining-lu** [comment]
Thanks!
