### ISSUE TITLE
Consider separating config building and codec building

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty-incubator-codec-quic#49]
We may want to consider separate config building and codec building as you want to use different configurations when creating different client without a new datagramchanel and a new pipeline.

**Comment by kachayev** [comment]
I'm not sure about the server but for the client this very question did bother me for quite some time. Even right now,  `QuicheQuicChannel::connect` function takes a pointer to configuration and this only time we actually need quiche config. So, I don't see obvious advantages of pairing config builder with codec builder accept, maybe, a user-facing API. If not the part of the codec, would be quiche config a part of `QuicheQuicChannel.QuicheQuicChannelAddress`?

**Comment by normanmaurer** [comment]
Let me experiment with this and open a DRAFT. Then we can have a look. I am not sure yet if it would be a good idea or not. I mean generally speaking it makes sense but I wonder if most people really need this and if it would not make things more complex for them.

**Comment by normanmaurer** [comment]
Ok I did some experiments and I think we should just keep it as it is. Seems flexible enough while not make things too complex
