### ISSUE TITLE
Your example is not difficult to connect to webtransport

### ISSUE THREAD

**Issue by redoriental** [netty/netty-incubator-codec-quic#492]
this.webTransPort = new WebTransport('https://redoriental.top:9999')

      await this.webTransPort.ready;

      this.webTransPort.closed
        .then(() => console.log('Connection closed normally'))
        .catch(error => console.log('Connection closed abruptly', error));

      // Create client-initiated bidi stream & writer
      this.stream = await this.webTransPort.createBidirectionalStream();
      this.writer = this.stream.writable.getWriter();

QuicSslContext context = QuicSslContextBuilder.forServer(
                        key, null, crt)
                .applicationProtocols(Http3.supportedApplicationProtocols()).earlyData(true).build();
        System.out.println(context.applicationProtocolNegotiator().protocols());
        NioEventLoopGroup group = new NioEventLoopGroup(1);
        //创建quic服务端编码器
        ChannelHandler codec = new QuicServerCodecBuilder().sslContext(context)
                .maxIdleTimeout(50000, TimeUnit.MILLISECONDS)
                //最大数量配置
                .initialMaxData(10000000)
                .initialMaxStreamDataBidirectionalLocal(1000000)
                .initialMaxStreamDataBidirectionalRemote(1000000)
                .initialMaxStreamsBidirectional(100)
                .initialMaxStreamsUnidirectional(100)
                // 设置一个令牌处理程序。在生产系统中，您可能希望实现和提供您的定制
                .tokenHandler(InsecureQuicTokenHandler.INSTANCE)
                //添加到QuicChannel管道中的ChannelHandler。
                .handler(new ChannelInboundHandlerAdapter() {
                    @Override
                    public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
                        if (evt instanceof QuicConnectionEvent) {
                            QuicConnectionEvent event = (QuicConnectionEvent) evt;
                            System.out.println(event.newAddress());
                        }
                    }
                    @Override
                    public void channelActive(ChannelHandlerContext ctx) throws Exception {
                        System.out.println("active");
                        ctx.writeAndFlush("sasasasa");
                    }

                    @Override
                    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
                        QuicChannel channel = (QuicChannel) ctx.channel();
                    }

                    @Override
                    public boolean isSharable() {
                        return true;
                    }
                    @Override
                    public void channelInactive(ChannelHandlerContext ctx) throws Exception {
                        ctx.fireChannelInactive();
                        System.out.println("关闭");
                    }
                })
                .streamHandler(new ChannelInitializer<QuicStreamChannel>() {
                    @Override
                    protected void initChannel(QuicStreamChannel ch)  {
                        System.out.println(2);
                        // 在这里添加一个LineBasedFrameDecoder，因为我们只是想做一些简单的HTTP 0.9处理。
                        ChannelPipeline pipeline = ch.pipeline();
                        pipeline.addLast(new ChannelInboundHandlerAdapter() {
                                    @Override
                                    public void channelRead(ChannelHandlerContext ctx, Object msg) {
                                        ByteBuf byteBuf = (ByteBuf) msg;
                                        byteBuf.release();
                                    }
                                });
                    }
                })
                .build();

        try {
            Bootstrap bs = new Bootstrap();
            Channel channel = bs.group(group)
                    .channel(NioDatagramChannel.class)
                    .handler(codec)
                    //设置端口号 9999
                    .bind(new InetSocketAddress(9999)).sync().channel();
            channel.closeFuture().sync();
        } finally {
            group.shutdownGracefully();
        }

**Comment by normanmaurer** [comment]
Please provide some more details. I am not sure what you are asking for .

**Comment by redoriental** [comment]
The code you provided cannot be connected to webtransport，I tried many times and couldn't shake hands

**Comment by normanmaurer** [comment]
Well we not support websockets over http3 so it's expected.

**Comment by redoriental** [comment]
"I hope you can support it quickly. The project you wrote is really excellent. I could have used webtransport-go as the server for webtransport, but go doesn't have such a good tool as javacv, so I still hope someone as powerful as you can get netty to support webtransport as soon as possible."

**Comment by normanmaurer** [comment]
its not a priority for me atm... That said we love contributions.
