### ISSUE TITLE
Unable to get peer certificates after handshake

### ISSUE THREAD

**Issue by ianopolous** [netty/netty-incubator-codec-quic#500]
I'm trying to get the peer certificates after the TLS handshake completes, but the session context is returning an empty enumeration for session ids. Is there a better way to get the certificates?

``` java
QuicSslContext sslContext = ...
// connect and complete handshake, then..
Enumeration<byte[]> ids = sslContext.sessionContext().getIds()   // This is empty
Certificate[] peerCerts = sslContext.sessionContext().getSession(ids.nextElement()).getPeerCertificates()
```

**Comment by normanmaurer** [comment]
This is currently not supported. You will need to retain a reference to the session by yourself.
