### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by Snowmaze-dev** [netty/netty-incubator-codec-quic#503]
I get this error when I try to build on Windows with any profile. Or does the artifact build only work on Linux now?
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (build-boringssl) on project netty-incubator-codec-native-quic: An Ant BuildException has occured: exec returned: 1
[ERROR] around Ant part ...<exec resolveexecutable="true" failonerror="true" dir="E:\IdeaProjects\netty-incubator-codec-quic\codec-native-quic\target/boringssl-source/build-target" executable="cmake">... @ 51:184 in E:\IdeaProjects\netty-incubator-codec-quic\codec-native-quic\target\antrun\build-main.xml
![Screenshot_107](https://user-images.githubusercontent.com/33610714/235381396-17a10f9c-0a40-42ad-ac57-38a1f2b5f319.png)

**Comment by normanmaurer** [comment]
Please check our window workflow.
