### ISSUE TITLE
Question about commons-codec dependency

### ISSUE THREAD

**Issue by kb-1000** [netty/netty-incubator-codec-quic#538]
This dependency is only used for HMAC. Its HMAC code appears to only be a simple wrapper around the Java stdlib's HMAC code, which raises a question to me - is an additional dependency really necessary here?

**Comment by normanmaurer** [comment]
Feel free to open a PR to change itAm 21.06.2023 um 05:35 schrieb kb1000 ***@***.***>:﻿
This dependency is only used for HMAC. Its HMAC code appears to only be a simple wrapper around the Java stdlib's HMAC code, which raises a question to me - is an additional dependency really necessary here?
