### ISSUE TITLE
Consider implementing LSQUIC servers with netty?

### ISSUE THREAD

**Issue by shiyangtao** [netty/netty-incubator-codec-quic#546]

**Comment by normanmaurer** [comment]
Why ?

**Comment by shiyangtao** [comment]
I want to implement lsquic through Netty and would like to refer to your approach, but I'm not sure how big the modification cost would be.

**Comment by normanmaurer** [comment]
You mean you want to use [LSQUIC](https://github.com/litespeedtech/lsquic) as a replacement for [quiche](https://github.com/cloudflare/quiche) ? If this is the case I can tell you it will be non-trivial as you would have to reimplement almost everything

**Comment by shiyangtao** [comment]
Yes, we want to implement a Java server based on lsquic, considering the high performance of Netty, so we would like to use Netty for implementation. Thank you.

**Comment by normanmaurer** [comment]
As said before this is not something we are currently consider.
