### ISSUE TITLE
the network transmission speed is extremely slow when the connection is just established

### ISSUE THREAD

**Issue by zhining-lu** [netty/netty-incubator-codec-quic#558]
If the delay between the client and the server is 200ms, the network transmission speed is extremely slow (about 100KB/s) when the connection is just established, After 20 seconds the speed increases to 10MB/s. The client operating environment is windows10, and the server operating environment is CentOS Stream release 9，file size is 100MB.

**Comment by normanmaurer** [comment]
@zhining-lu what are the settings ? Also did you see https://github.com/netty/netty-incubator-codec-quic/issues/598 ?

**Comment by Acheat** [comment]
It is more likely that the quche initialization window is too small and cannot grow well under high latency. And there is no place to set it.

**Comment by normanmaurer** [comment]
@Acheat what window you are talking about ? We expose all the configurations that can be set for quiche via our builder.

**Comment by normanmaurer** [comment]
Let's close this for now
