### ISSUE TITLE
Quic server very slow compared to TCP

### ISSUE THREAD

**Issue by DanielAlmeidaJoao** [netty/netty-incubator-codec-quic#575]
Hello,

I have a simple netty client-server application to stream a 1GB file, and I noticed that the one using QUIC is extremely lower than
the one using TCP, for example, the TCP server application takes 4 seconds to read all the bytes of the file from the client, while the QUIC server takes 8 seconds.

What is happening? Is quic supposed to be this much slower than TCP ?
Have you tested the speed of this quic-netty-incubator implementation vs the TCP offered by netty ?

**Comment by normanmaurer** [comment]
Yes I have tested it and yes its slower then TCP. That said it's also not fair to compare both as QUIC also includes encryption etc.

**Comment by normanmaurer** [comment]
Beside this you also want to use GSO etc

**Comment by normanmaurer** [comment]
This might be a duplicate of https://github.com/netty/netty-incubator-codec-quic/issues/598

**Comment by DanielAlmeidaJoao** [comment]
What is a GSO ?
