### ISSUE TITLE
Quick server reception speed is slow

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty-incubator-codec-quic#598]
I use go quic as the client to send data to Java quic server. The file size is 767MB, which takes 29 seconds. Golang sends the data and shows that the stream is closed after 24 seconds. Java has a 5-second lifecycle, which takes 29 seconds. The actual result is 767MB, which takes 24 seconds. The quic server debug log has been closed, and the network environment is 127.0.0.1 native. Why is it so slow?

```
package net.hserver.hp.proxy.test;

import io.netty.bootstrap.Bootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.channel.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.nio.NioDatagramChannel;
import io.netty.handler.codec.LineBasedFrameDecoder;
import io.netty.handler.logging.LogLevel;
import io.netty.handler.logging.LoggingHandler;
import io.netty.handler.ssl.util.SelfSignedCertificate;
import io.netty.incubator.codec.quic.*;
import io.netty.util.CharsetUtil;
import io.netty.util.internal.logging.InternalLogger;
import io.netty.util.internal.logging.InternalLoggerFactory;

import java.net.InetSocketAddress;
import java.util.concurrent.TimeUnit;

public  class QuicServerExample {

    private static final InternalLogger LOGGER = InternalLoggerFactory.getInstance(QuicServerExample.class);

    private QuicServerExample() {
    }

    public static void main(String[] args) throws Exception {
        SelfSignedCertificate selfSignedCertificate = new SelfSignedCertificate();
        QuicSslContext context = QuicSslContextBuilder.forServer(
                        selfSignedCertificate.privateKey(), null, selfSignedCertificate.certificate())
                .applicationProtocols("HP_PRO").build();
        NioEventLoopGroup group = new NioEventLoopGroup(1);
        ChannelHandler codec = new QuicServerCodecBuilder().sslContext(context)
                .maxIdleTimeout(5000, TimeUnit.MILLISECONDS)
                // Configure some limits for the maximal number of streams (and the data) that we want to handle.
                .initialMaxData(10000000)
                .initialMaxStreamDataBidirectionalLocal(1000000)
                .initialMaxStreamDataBidirectionalRemote(1000000)
                .initialMaxStreamsBidirectional(100)
                .initialMaxStreamsUnidirectional(100)

                // Setup a token handler. In a production system you would want to implement and provide your custom
                // one.
                .tokenHandler(InsecureQuicTokenHandler.INSTANCE)
                // ChannelHandler that is added into QuicChannel pipeline.
                .handler(new LoggingHandler(LogLevel.INFO))
                .handler(new ChannelInboundHandlerAdapter() {
                    @Override
                    public void channelActive(ChannelHandlerContext ctx) {
                        QuicChannel channel = (QuicChannel) ctx.channel();
                        // Create streams etc..
                    }

                    public void channelInactive(ChannelHandlerContext ctx) {
                        ((QuicChannel) ctx.channel()).collectStats().addListener(f -> {
                            if (f.isSuccess()) {
                                LOGGER.info("Connection closed: {}", f.getNow());
                            }
                        });
                    }

                    @Override
                    public boolean isSharable() {
                        return true;
                    }
                })
                .streamHandler(new ChannelInitializer<QuicStreamChannel>() {
                    @Override
                    protected void initChannel(QuicStreamChannel ch) {
                        ch.pipeline().addLast(new ChannelInboundHandlerAdapter() {

                            private long start = 0;

                            @Override
                            public void channelActive(ChannelHandlerContext ctx) throws Exception {
                                super.channelActive(ctx);
                                start = System.currentTimeMillis();
                                System.out.println("startTime");
                            }

                            @Override
                            public void channelInactive(ChannelHandlerContext ctx) throws Exception {
                                super.channelInactive(ctx);
                                System.out.println("endTime：" + (System.currentTimeMillis() - start));
                            }

                            @Override
                            public void channelRead(ChannelHandlerContext ctx, Object msg) {
                                ByteBuf byteBuf = (ByteBuf) msg;
                                try {

                                } finally {
                                    byteBuf.release();
                                }
                            }
                        });
                    }
                }).build();
        try {
            Bootstrap bs = new Bootstrap();
            Channel channel = bs.group(group)
                    .channel(NioDatagramChannel.class)
                    .handler(codec)
                    .bind(new InetSocketAddress(9999)).sync().channel();
            channel.closeFuture().sync();
        } finally {
            group.shutdownGracefully();
        }
    }
}


```
package main

import (
	"context"
	"crypto/tls"
	"fmt"
	"github.com/quic-go/quic-go"
	"os"
	"time"
)

func main() {
	tlsConf := &tls.Config{
		InsecureSkipVerify: true,
		NextProtos:         []string{"HP_PRO"},
	}
	conn, err := quic.DialAddr(context.Background(), "127.0.0.1:9999", tlsConf, nil)
	if err != nil {
		fmt.Printf(err.Error())
		return
	}

	stream, err := conn.OpenStreamSync(context.Background())
	if err != nil {
		fmt.Printf(err.Error())
	}

	file, err := os.Open("/Users/heixiaoma/Downloads/aaa.mkv.7")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer file.Close()
	buffer := make([]byte, 1024)
	start := time.Now()
	for {
		bytesRead, err := file.Read(buffer)
		if err != nil {
			fmt.Println(err)
			break
		}
		if bytesRead == 0 {
			break
		}
		_, err = stream.Write(buffer)
		if err != nil {
			fmt.Println(err)
			break
		}
	}
	elapsed := time.Since(start)
	fmt.Printf("end：%s\n", elapsed)
	stream.Close()
	if err != nil {
		fmt.Printf(err.Error())
	}

}

```

```

**Comment by normanmaurer** [comment]
Sorry I am not sure I get the question... you are asking why it takes 24 seconds ?

**Comment by heixiaoma** [comment]
> 抱歉，我不确定我是否明白这个问题...您是在问为什么需要 24 秒？



> Sorry I am not sure I get the question... you are asking why it takes 24 seconds ?

Yes, why does it take 24 seconds? 767/24=31.9 mb/s, does it require some optimization to improve the speed? TCP can reach 100mb/s

**Comment by heixiaoma** [comment]
go-quic-client-> go-quic-server, 767mb file takes 8 seconds, is a satisfactory speed, go-quic-client-> java-quic-server, takes 24 seconds, java-quic-client-> java-quic-server takes about 30 seconds

**Comment by normanmaurer** [comment]
@heixiaoma are you sure you use the same settings in terms of limits etc ? Also can you share on what OS this is ?

**Comment by heixiaoma** [comment]
> @heixiaoma are you sure you use the same settings in terms of limits etc ? Also can you share on what OS this is ?


Yes, they all have the same configuration, and I am using the Mac OS

**Comment by normanmaurer** [comment]
Can you share the code for the client / server in go as well so I can reproduce it here ?

**Comment by heixiaoma** [comment]
> Can you share the code for the client / server in go as well so I can reproduce it here ?

![image](https://github.com/netty/netty-incubator-codec-quic/assets/10923974/8a07327d-7665-40f1-969e-23bd2e5931a1)

This is a screenshot of Win10 Intel (R) Core (TM) i7-9700K CPU @ 3.60GHz 3.60 transferring 1GB files, which takes 49.9 seconds

**Comment by heixiaoma** [comment]
> Can you share the code for the client / server in go as well so I can reproduce it here ?

``` golang

package main

import (
	"context"
	"crypto/tls"
	"fmt"
	"github.com/quic-go/quic-go"
	"os"
	"time"
)

func main() {
	tlsConf := &tls.Config{
		InsecureSkipVerify: true,
		NextProtos:         []string{"HP_PRO"},
	}
	conn, err := quic.DialAddr(context.Background(), "127.0.0.1:9999", tlsConf, nil)
	if err != nil {
		fmt.Printf(err.Error())
		return
	}

	stream, err := conn.OpenStreamSync(context.Background())
	if err != nil {
		fmt.Printf(err.Error())
	}

	fmt.Printf("Client: Sending '%s'\n", "message")

	file, err := os.Open("F:\\Goole浏览器\\aa (4).mkv")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer file.Close()
	buffer := make([]byte, 2048)
	start := time.Now()
	for {
		bytesRead, err := file.Read(buffer)
		if err != nil {
			fmt.Println(err)
			break
		}
		if bytesRead == 0 {
			break
		}
		_, err = stream.Write(buffer)
		if err != nil {
			fmt.Println(err)
			break
		}
	}
	elapsed := time.Since(start)
	fmt.Printf("time：%s\n", elapsed)
	stream.Close()
	if err != nil {
		fmt.Printf(err.Error())
	}

}


```


``` java
import io.netty.bootstrap.Bootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.channel.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.nio.NioDatagramChannel;
import io.netty.handler.logging.LogLevel;
import io.netty.handler.logging.LoggingHandler;
import io.netty.handler.ssl.util.SelfSignedCertificate;
import io.netty.incubator.codec.quic.*;
import io.netty.util.internal.logging.InternalLogger;
import io.netty.util.internal.logging.InternalLoggerFactory;

import java.net.InetSocketAddress;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.LongAdder;

public  class QuicServerExample {

    private static final InternalLogger LOGGER = InternalLoggerFactory.getInstance(QuicServerExample.class);

    private QuicServerExample() {
    }

    public static void main(String[] args) throws Exception {
        SelfSignedCertificate selfSignedCertificate = new SelfSignedCertificate();
        QuicSslContext context = QuicSslContextBuilder.forServer(
                        selfSignedCertificate.privateKey(), null, selfSignedCertificate.certificate())
                .applicationProtocols("HP_PRO").build();
        NioEventLoopGroup group = new NioEventLoopGroup(1);
        ChannelHandler codec = new QuicServerCodecBuilder().sslContext(context)
                .maxIdleTimeout(5000, TimeUnit.MILLISECONDS)
                // Configure some limits for the maximal number of streams (and the data) that we want to handle.
                .initialMaxData(100000)
                .initialMaxStreamDataBidirectionalLocal(1000000)
                .initialMaxStreamDataBidirectionalRemote(1000000)
                .initialMaxStreamsBidirectional(100)
                .initialMaxStreamsUnidirectional(100)

                // Setup a token handler. In a production system you would want to implement and provide your custom
                // one.
                .tokenHandler(InsecureQuicTokenHandler.INSTANCE)
                // ChannelHandler that is added into QuicChannel pipeline.
                .handler(new LoggingHandler(LogLevel.INFO))
                .handler(new ChannelInboundHandlerAdapter() {
                    @Override
                    public void channelActive(ChannelHandlerContext ctx) {
                        QuicChannel channel = (QuicChannel) ctx.channel();
                        // Create streams etc..
                    }

                    public void channelInactive(ChannelHandlerContext ctx) {
                        ((QuicChannel) ctx.channel()).collectStats().addListener(f -> {
                            if (f.isSuccess()) {
                                LOGGER.info("Connection closed: {}", f.getNow());
                            }
                        });
                    }

                    @Override
                    public boolean isSharable() {
                        return true;
                    }
                })
                .streamHandler(new ChannelInitializer<QuicStreamChannel>() {
                    @Override
                    protected void initChannel(QuicStreamChannel ch) {
                        ch.pipeline().addLast(new ChannelInboundHandlerAdapter() {

                            private long start = 0;
                            private LongAdder size = new LongAdder();

                            @Override
                            public void channelActive(ChannelHandlerContext ctx) throws Exception {
                                super.channelActive(ctx);
                                start = System.currentTimeMillis();
                                System.out.println("startTime");
                            }

                            @Override
                            public void channelInactive(ChannelHandlerContext ctx) throws Exception {
                                super.channelInactive(ctx);
                                System.out.println(size);
                                System.out.println("endTime：" + (System.currentTimeMillis() - start));
                            }

                            @Override
                            public void channelRead(ChannelHandlerContext ctx, Object msg) {
                                ByteBuf byteBuf = (ByteBuf) msg;
                                try {
                                    size.add(byteBuf.readableBytes());
                                } finally {
                                    byteBuf.release();
                                }
                            }
                        });
                    }
                }).build();
        try {
            Bootstrap bs = new Bootstrap();
            Channel channel = bs.group(group)
                    .channel(NioDatagramChannel.class)
                    .handler(codec)
                    .bind(new InetSocketAddress(9999)).sync().channel();
            channel.closeFuture().sync();
        } finally {
            group.shutdownGracefully();
        }
    }
}


```

**Comment by heixiaoma** [comment]
> 您能否也分享 go 中客户端/服务器的代码，以便我可以在这里重现它？

``` golang
package main

import (
	"bufio"
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"github.com/quic-go/quic-go"
	"io"
	"math/big"
	"os"
	"time"
)

const addr = "localhost:4242"

const message = "foobar"

func generateTLSConfig() *tls.Config {
	key, err := rsa.GenerateKey(rand.Reader, 1024)
	if err != nil {
		panic(err)
	}
	template := x509.Certificate{SerialNumber: big.NewInt(1)}
	certDER, err := x509.CreateCertificate(rand.Reader, &template, &template, &key.PublicKey, key)
	if err != nil {
		panic(err)
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)})
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certDER})

	tlsCert, err := tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		panic(err)
	}
	return &tls.Config{
		Certificates: []tls.Certificate{tlsCert},
		NextProtos:   []string{"HP_PRO"},
	}
}
func server() {
	listener, err := quic.ListenAddr(addr, generateTLSConfig(), nil)
	if err != nil {
		println(err.Error())
	}
	conn, err := listener.Accept(context.Background())
	if err != nil {
		println(err.Error())

	}
	stream, err := conn.AcceptStream(context.Background())
	if err != nil {
		println(err.Error())
	}
	reader := bufio.NewReader(stream)
	start := time.Now()

	for {
		//尝试读检查连接激活
		_, err := reader.Peek(1)
		if err != nil {
			break
		}
		data := make([]byte, reader.Buffered())
		io.ReadFull(reader, data)
	}
	elapsed := time.Since(start)
	fmt.Printf("接收耗时：%s\n", elapsed)
}

func client() {
	tlsConf := &tls.Config{
		InsecureSkipVerify: true,
		NextProtos:         []string{"HP_PRO"},
	}
	conn, err := quic.DialAddr(context.Background(), addr, tlsConf, nil)
	if err != nil {
		fmt.Printf(err.Error())
		return
	}

	stream, err := conn.OpenStreamSync(context.Background())
	if err != nil {
		fmt.Printf(err.Error())
	}

	fmt.Printf("Client: Sending '%s'\n", "message")

	file, err := os.Open("/Users/heixiaoma/Downloads/阴阳画皮.mkv.7")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer file.Close()
	buffer := make([]byte, 2048)
	start := time.Now()
	for {
		bytesRead, err := file.Read(buffer)
		if err != nil {
			fmt.Println(err)
			break
		}
		if bytesRead == 0 {
			break
		}
		_, err = stream.Write(buffer)
		if err != nil {
			fmt.Println(err)
			break
		}
	}
	elapsed := time.Since(start)
	fmt.Printf("发送耗时：%s\n", elapsed)
	stream.Close()
	if err != nil {
		fmt.Printf(err.Error())
	}

}

func main() {
	go server()
	go client()
	select {}
}

```

**Comment by heixiaoma** [comment]
> 您是否还可以分享去中客户端/服务器的代码，以便我可以在这里重置它？

![image](https://github.com/netty/netty-incubator-codec-quic/assets/10923974/5d7bf2b0-76cd-42d4-acc4-7b8407984acd)
Golang only takes 16 seconds to send 1G files

**Comment by heixiaoma** [comment]
> Can you share the code for the client / server in go as well so I can reproduce it here ?

Thank you for your support. My technical level is limited and I cannot reproduce the specific reason. Thank you for your support of open source

**Comment by normanmaurer** [comment]
@heixiaoma I am not a go developer... Can you create a go project and share that I can just compile / run myself ? Basically a project with your shared code but that also have all the build scripts etc included

**Comment by heixiaoma** [comment]
> @heixiaoma I am not a go developer... Can you create a go project and share that I can just compile / run myself ? Basically a project with your shared code but that also have all the build scripts etc included

Okay, I'll create the test project now

**Comment by heixiaoma** [comment]
> @heixiaoma I am not a go developer... Can you create a go project and share that I can just compile / run myself ? Basically a project with your shared code but that also have all the build scripts etc included

https://github.com/heixiaoma/go-quic-test

**Comment by normanmaurer** [comment]
Please try this server code:

```
public final class QuicServerReadExample {

    private static final InternalLogger LOGGER = InternalLoggerFactory.getInstance(QuicServerReadExample.class);

    private QuicServerReadExample() { }

    public static void main(String[] args) throws Exception {
        SelfSignedCertificate selfSignedCertificate = new SelfSignedCertificate();
        QuicSslContext context = QuicSslContextBuilder.forServer(
                selfSignedCertificate.privateKey(), null, selfSignedCertificate.certificate())
                .applicationProtocols("HP_PRO").build();
        NioEventLoopGroup group = new NioEventLoopGroup(1);
        ChannelHandler codec = new QuicServerCodecBuilder().sslContext(context)
                .maxIdleTimeout(5000, TimeUnit.MILLISECONDS)
                // Configure some limits for the maximal number of streams (and the data) that we want to handle.
                .initialMaxData(1000000000)
                .initialMaxStreamDataBidirectionalRemote(1000000000)
                .initialMaxStreamsBidirectional(100)
                .initialMaxStreamsUnidirectional(100)

                // Setup a token handler. In a production system you would want to implement and provide your custom
                // one.
                .tokenHandler(InsecureQuicTokenHandler.INSTANCE)
                // ChannelHandler that is added into QuicChannel pipeline.
                .handler(new ChannelInboundHandlerAdapter() {
                    @Override
                    public void channelInactive(ChannelHandlerContext ctx) {
                        ((QuicChannel) ctx.channel()).collectStats().addListener(f -> {
                            if (f.isSuccess()) {
                                LOGGER.info("Connection closed: {}", f.getNow());
                            }
                        });
                    }

                    @Override
                    public boolean isSharable() {
                        return true;
                    }
                })
                .streamHandler(new ChannelInitializer<QuicStreamChannel>() {
                    @Override
                    protected void initChannel(QuicStreamChannel ch)  {
                        // Add a LineBasedFrameDecoder here as we just want to do some simple HTTP 0.9 handling.
                        ch.pipeline()
                                .addLast(new ChannelInboundHandlerAdapter() {
                                    private long start;
                                    @Override
                                    public void channelRead(ChannelHandlerContext ctx, Object msg) {
                                        ReferenceCountUtil.release(msg);
                                    }

                                    @Override
                                    public void channelActive(ChannelHandlerContext ctx) {
                                        start = System.nanoTime();
                                        ctx.fireChannelActive();
                                    }

                                    @Override
                                    public void userEventTriggered(ChannelHandlerContext ctx, Object evt) {
                                        ctx.fireUserEventTriggered(evt);
                                        if (evt instanceof ChannelInputShutdownReadComplete) {
                                            // We received the FIN of the remove peer. This means everything was read. Let's call close() so we also send the FIN.
                                            System.err.println("It takes time to read: " + TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - start) + "ms");
                                            ctx.close();
                                        }
                                    }
                                });
                    }
                })
                .build();
        try {
            Bootstrap bs = new Bootstrap();
            Channel channel = bs.group(group)
                    .channel(NioDatagramChannel.class)
                    .handler(codec)
                    .option(ChannelOption.MAX_MESSAGES_PER_READ, Integer.MAX_VALUE)
                    .bind(new InetSocketAddress(4242)).sync().channel();
            channel.closeFuture().sync();
        } finally {
            group.shutdownGracefully();
        }
    }
```

This actually outperforms the go server code. There were two problems with your code, one I think is a bug on our side but the other is a bug in your code.

This should not be needed and I will look into fixing it on our side.
```
.option(ChannelOption.MAX_MESSAGES_PER_READ, Integer.MAX_VALUE)
```

The bug in your code was that you used `channelInactive(...)` for detecting when the remote peer is done sending and we did read everything. This is incorrect as this is only called when the input and output is closed (which means when we received a FIN and also send a FIN). You want to use `userEventTriggered(...)` to detect that the remote peer did sent a FIN.

**Comment by heixiaoma** [comment]
![Uploading image.png…]()
I did notice that enabling this setting made the build much faster. However, I saw that this setting is deprecated. Is there a better way to configure this parameter?

**Comment by heixiaoma** [comment]
> Please try this server code:
> 
> ```
> public final class QuicServerReadExample {
> 
>     private static final InternalLogger LOGGER = InternalLoggerFactory.getInstance(QuicServerReadExample.class);
> 
>     private QuicServerReadExample() { }
> 
>     public static void main(String[] args) throws Exception {
>         SelfSignedCertificate selfSignedCertificate = new SelfSignedCertificate();
>         QuicSslContext context = QuicSslContextBuilder.forServer(
>                 selfSignedCertificate.privateKey(), null, selfSignedCertificate.certificate())
>                 .applicationProtocols("HP_PRO").build();
>         NioEventLoopGroup group = new NioEventLoopGroup(1);
>         ChannelHandler codec = new QuicServerCodecBuilder().sslContext(context)
>                 .maxIdleTimeout(5000, TimeUnit.MILLISECONDS)
>                 // Configure some limits for the maximal number of streams (and the data) that we want to handle.
>                 .initialMaxData(1000000000)
>                 .initialMaxStreamDataBidirectionalRemote(1000000000)
>                 .initialMaxStreamsBidirectional(100)
>                 .initialMaxStreamsUnidirectional(100)
> 
>                 // Setup a token handler. In a production system you would want to implement and provide your custom
>                 // one.
>                 .tokenHandler(InsecureQuicTokenHandler.INSTANCE)
>                 // ChannelHandler that is added into QuicChannel pipeline.
>                 .handler(new ChannelInboundHandlerAdapter() {
>                     @Override
>                     public void channelInactive(ChannelHandlerContext ctx) {
>                         ((QuicChannel) ctx.channel()).collectStats().addListener(f -> {
>                             if (f.isSuccess()) {
>                                 LOGGER.info("Connection closed: {}", f.getNow());
>                             }
>                         });
>                     }
> 
>                     @Override
>                     public boolean isSharable() {
>                         return true;
>                     }
>                 })
>                 .streamHandler(new ChannelInitializer<QuicStreamChannel>() {
>                     @Override
>                     protected void initChannel(QuicStreamChannel ch)  {
>                         // Add a LineBasedFrameDecoder here as we just want to do some simple HTTP 0.9 handling.
>                         ch.pipeline()
>                                 .addLast(new ChannelInboundHandlerAdapter() {
>                                     private long start;
>                                     @Override
>                                     public void channelRead(ChannelHandlerContext ctx, Object msg) {
>                                         ReferenceCountUtil.release(msg);
>                                     }
> 
>                                     @Override
>                                     public void channelActive(ChannelHandlerContext ctx) {
>                                         start = System.nanoTime();
>                                         ctx.fireChannelActive();
>                                     }
> 
>                                     @Override
>                                     public void userEventTriggered(ChannelHandlerContext ctx, Object evt) {
>                                         ctx.fireUserEventTriggered(evt);
>                                         if (evt instanceof ChannelInputShutdownReadComplete) {
>                                             // We received the FIN of the remove peer. This means everything was read. Let's call close() so we also send the FIN.
>                                             System.err.println("It takes time to read: " + TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - start) + "ms");
>                                             ctx.close();
>                                         }
>                                     }
>                                 });
>                     }
>                 })
>                 .build();
>         try {
>             Bootstrap bs = new Bootstrap();
>             Channel channel = bs.group(group)
>                     .channel(NioDatagramChannel.class)
>                     .handler(codec)
>                     .option(ChannelOption.MAX_MESSAGES_PER_READ, Integer.MAX_VALUE)
>                     .bind(new InetSocketAddress(4242)).sync().channel();
>             channel.closeFuture().sync();
>         } finally {
>             group.shutdownGracefully();
>         }
>     }
> ```
> 
> This actually outperforms the go server code. There were two problems with your code, one I think is a bug on our side but the other is a bug in your code.
> 
> This should not be needed and I will look into fixing it on our side.
> 
> ```
> .option(ChannelOption.MAX_MESSAGES_PER_READ, Integer.MAX_VALUE)
> ```
> 
> The bug in your code was that you used `channelInactive(...)` for detecting when the remote peer is done sending and we did read everything. This is incorrect as this is only called when the input and output is closed (which means when we received a FIN and also send a FIN). You want to use `userEventTriggered(...)` to detect that the remote peer did sent a FIN.

I did notice that enabling this setting made the build much faster. However, I saw that this setting is deprecated. Is there a better way to configure this parameter?

**Comment by heixiaoma** [comment]
> Please try this server code:
> 
> ```
> public final class QuicServerReadExample {
> 
>     private static final InternalLogger LOGGER = InternalLoggerFactory.getInstance(QuicServerReadExample.class);
> 
>     private QuicServerReadExample() { }
> 
>     public static void main(String[] args) throws Exception {
>         SelfSignedCertificate selfSignedCertificate = new SelfSignedCertificate();
>         QuicSslContext context = QuicSslContextBuilder.forServer(
>                 selfSignedCertificate.privateKey(), null, selfSignedCertificate.certificate())
>                 .applicationProtocols("HP_PRO").build();
>         NioEventLoopGroup group = new NioEventLoopGroup(1);
>         ChannelHandler codec = new QuicServerCodecBuilder().sslContext(context)
>                 .maxIdleTimeout(5000, TimeUnit.MILLISECONDS)
>                 // Configure some limits for the maximal number of streams (and the data) that we want to handle.
>                 .initialMaxData(1000000000)
>                 .initialMaxStreamDataBidirectionalRemote(1000000000)
>                 .initialMaxStreamsBidirectional(100)
>                 .initialMaxStreamsUnidirectional(100)
> 
>                 // Setup a token handler. In a production system you would want to implement and provide your custom
>                 // one.
>                 .tokenHandler(InsecureQuicTokenHandler.INSTANCE)
>                 // ChannelHandler that is added into QuicChannel pipeline.
>                 .handler(new ChannelInboundHandlerAdapter() {
>                     @Override
>                     public void channelInactive(ChannelHandlerContext ctx) {
>                         ((QuicChannel) ctx.channel()).collectStats().addListener(f -> {
>                             if (f.isSuccess()) {
>                                 LOGGER.info("Connection closed: {}", f.getNow());
>                             }
>                         });
>                     }
> 
>                     @Override
>                     public boolean isSharable() {
>                         return true;
>                     }
>                 })
>                 .streamHandler(new ChannelInitializer<QuicStreamChannel>() {
>                     @Override
>                     protected void initChannel(QuicStreamChannel ch)  {
>                         // Add a LineBasedFrameDecoder here as we just want to do some simple HTTP 0.9 handling.
>                         ch.pipeline()
>                                 .addLast(new ChannelInboundHandlerAdapter() {
>                                     private long start;
>                                     @Override
>                                     public void channelRead(ChannelHandlerContext ctx, Object msg) {
>                                         ReferenceCountUtil.release(msg);
>                                     }
> 
>                                     @Override
>                                     public void channelActive(ChannelHandlerContext ctx) {
>                                         start = System.nanoTime();
>                                         ctx.fireChannelActive();
>                                     }
> 
>                                     @Override
>                                     public void userEventTriggered(ChannelHandlerContext ctx, Object evt) {
>                                         ctx.fireUserEventTriggered(evt);
>                                         if (evt instanceof ChannelInputShutdownReadComplete) {
>                                             // We received the FIN of the remove peer. This means everything was read. Let's call close() so we also send the FIN.
>                                             System.err.println("It takes time to read: " + TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - start) + "ms");
>                                             ctx.close();
>                                         }
>                                     }
>                                 });
>                     }
>                 })
>                 .build();
>         try {
>             Bootstrap bs = new Bootstrap();
>             Channel channel = bs.group(group)
>                     .channel(NioDatagramChannel.class)
>                     .handler(codec)
>                     .option(ChannelOption.MAX_MESSAGES_PER_READ, Integer.MAX_VALUE)
>                     .bind(new InetSocketAddress(4242)).sync().channel();
>             channel.closeFuture().sync();
>         } finally {
>             group.shutdownGracefully();
>         }
>     }
> ```
> 
> This actually outperforms the go server code. There were two problems with your code, one I think is a bug on our side but the other is a bug in your code.
> 
> This should not be needed and I will look into fixing it on our side.
> 
> ```
> .option(ChannelOption.MAX_MESSAGES_PER_READ, Integer.MAX_VALUE)
> ```
> 
> The bug in your code was that you used `channelInactive(...)` for detecting when the remote peer is done sending and we did read everything. This is incorrect as this is only called when the input and output is closed (which means when we received a FIN and also send a FIN). You want to use `userEventTriggered(...)` to detect that the remote peer did sent a FIN.

![image](https://github.com/netty/netty-incubator-codec-quic/assets/10923974/8cfa07d6-8341-4834-89e6-41d09f92e0f8)

**Comment by normanmaurer** [comment]
@heixiaoma yes...

```
 try {
            FixedRecvByteBufAllocator recvByteBufAllocator = new FixedRecvByteBufAllocator(2048);
            recvByteBufAllocator.maxMessagesPerRead(Integer.MAX_VALUE);
            Bootstrap bs = new Bootstrap();
            Channel channel = bs.group(group)
                    .channel(NioDatagramChannel.class)
                    .handler(codec)
                    .option(ChannelOption.RCVBUF_ALLOCATOR, recvByteBufAllocator)
                    .bind(new InetSocketAddress(4242)).sync().channel();
            channel.closeFuture().sync();
        } finally {
            group.shutdownGracefully();
        }
```

**Comment by heixiaoma** [comment]
> @heixiaoma是的...
> 
> ```
>  try {
>             FixedRecvByteBufAllocator recvByteBufAllocator = new FixedRecvByteBufAllocator(2048);
>             recvByteBufAllocator.maxMessagesPerRead(Integer.MAX_VALUE);
>             Bootstrap bs = new Bootstrap();
>             Channel channel = bs.group(group)
>                     .channel(NioDatagramChannel.class)
>                     .handler(codec)
>                     .option(ChannelOption.RCVBUF_ALLOCATOR, recvByteBufAllocator)
>                     .bind(new InetSocketAddress(4242)).sync().channel();
>             channel.closeFuture().sync();
>         } finally {
>             group.shutdownGracefully();
>         }
> ```

Thank you for your help. It seems that I need to delve deeper into this parameter in order to better use this framework
