### ISSUE TITLE
When Path challenge happens, quiche's old peer address is different from netty's old peer address

### ISSUE THREAD

**Issue by PeakerChen** [netty/netty-incubator-codec-quic#612]
[v1] [2023-11-10 17:43:28.019] [DEBUG] [epollEventLoopGroup-2-1] Quiche [TID: N/A] quiche: 8159df8b06ae79c613e54f4e173736bec45052cb 
reused CID seq 0 of **(0.0.0.0:16685,39.144.80.12:40201) (path 0) on (0.0.0.0:16685,39.144.80.54:3080)**
[v1] [2023-11-10 17:43:28.088] [INFO ] [epollEventLoopGroup-2-1] QUICConnectionHandler [TID: N/A] quic connection migrate ,
new address **: [39.144.80.54:2060], old address: [39.144.80.54:2060]**

**Comment by normanmaurer** [comment]
Can you share a reproducer ?Am 13.11.2023 um 12:25 schrieb Peaker Chen ***@***.***>:﻿
[v1] [2023-11-10 17:43:28.019] [DEBUG] [epollEventLoopGroup-2-1] Quiche [TID: N/A] quiche: 8159df8b06ae79c613e54f4e173736bec45052cb
reused CID seq 0 of (0.0.0.0:16685,39.144.80.12:40201) (path 0) on (0.0.0.0:16685,39.144.80.54:3080)
[v1] [2023-11-10 17:43:28.088] [INFO ] [epollEventLoopGroup-2-1] QUICConnectionHandler [TID: N/A] quic connection migrate ,
new address: [39.144.80.54:2060], old address: [39.144.80.54:2060]

**Comment by normanmaurer** [comment]
@PeakerChen can you tell me how to retrieve the quiche address and also how you retrieve the netty address ? Is the netty related stuff via `QuicConnectionEvent` ?

**Comment by PeakerChen** [comment]
the quiche addresss  via quiche debug log and the netty address via QuicConnectionEvent

**Comment by normanmaurer** [comment]
@PeakerChen what about the "new address" ? Does it match ?

**Comment by normanmaurer** [comment]
Also even thought the address is different does everything still work ? Or is the communication not working anymore ?

**Comment by normanmaurer** [comment]
Also is this client or server ?

**Comment by PeakerChen** [comment]
even thought the address is different does everything still work, the communication is working.
It's a server.

**Comment by PeakerChen** [comment]
Here‘s another weird question. Why is the old and new address the same in QuicConnectionEvent

**Comment by normanmaurer** [comment]
@PeakerChen yeah that is what I try to understand :/  Can you attach debugger and see from where the event is fired ? Like is it while receiving or while sending ?

**Comment by PeakerChen** [comment]
Yes, I can. My codes register QuicConnectionEvent，and the QuicConnectionEvent was triggered by QuicheQuicChannel.QuicChannelUnsafe.connectionRecv(**). 
If the remote address was changed, the QuicConnectionEvent would be triggered.
![Uploading image.png…]()

**Comment by normanmaurer** [comment]
I suspect the reason is that this might only be a probe but it's not validated yet by the server. Let me double check

**Comment by normanmaurer** [comment]
I really have a hard time to understand how this could happen. Can you please add a `new Throwable().printStacktrace()` to the place where you intercept the `QuicConnectionEvent` and paste the resulting stack trace ?
