### ISSUE TITLE
QuicConnectionEvent is gone

### ISSUE THREAD

**Issue by zipper01** [netty/netty-incubator-codec-quic#632]
I just moved from netty-incubator-codec-native-quic `0.0.35.Final` to `0.0.53.Final` and io.netty.incubator.codec.quic.QuicConnectionEvent is gone. See also this thread: [[netty-incubator-codec-quic: How to get remoteAddress?](https://stackoverflow.com/questions/70944286/netty-incubator-codec-quic-how-to-get-remoteaddress)](https://stackoverflow.com/questions/70944286/netty-incubator-codec-quic-how-to-get-remoteaddress)

**Comment by normanmaurer** [comment]
Yes... Check https://netty.io/news/2023/11/30/quic-0-0-53-Final.html
