### ISSUE TITLE
QuicPathEvent event how to trigger？

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty-incubator-codec-quic#654]
The commented code was previously used to obtain the IP address, which has now been removed and updated to QuicPathEvent. I found that this event does not get triggered when a user connects and sends a message. What I observed instead are: :io.netty.handler.ssl.SslHandshakeCompletionEvent and io.netty.incubator.codec.quic.QuicStreamLimitChangedEvent, but the QuicPathEvent event does not get triggered.
```
    @Override
    public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
//        if (evt instanceof QuicConnectionEvent) {
//            QuicConnectionEvent event = (QuicConnectionEvent) evt;
//            ctx.channel().attr(IP_ADDRESS).set((InetSocketAddress) event.newAddress());
//        }

        if (evt instanceof QuicPathEvent) {
            QuicPathEvent event = (QuicPathEvent) evt;
            ctx.channel().attr(IP_ADDRESS).set(event.remote());
        }
    }

```

**Comment by heixiaoma** [comment]
Or maybe my method of obtaining the IP address is outdated, and there is now a better solution for acquiring it?

**Comment by normanmaurer** [comment]
override `channelActive(...)`
