### ISSUE TITLE
How to obtain remote IP addresses for QUIC？

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty-incubator-codec-quic#662]
handler->channelActive
QuicConnectionAddress{connId=0670c605321a6bb6204ce71fd0ee7c789ebc7d88}

streamHandler->channelActive
QuicStreamAddress{streamId=0}

QuicConnectionAddress and QuicStreamAddress inherit SocketAddress, but they do not have IP address related information

**Comment by heixiaoma** [comment]
![image](https://github.com/netty/netty-incubator-codec-quic/assets/10923974/b766ca28-51bd-43af-b4c4-aede2c2fa5db)

Why is the class io.netty.incubator.codec.quic.QuicheQuicChannel designed as final?


Currently, remote values can be obtained through reflection

**Comment by normanmaurer** [comment]
@heixiaoma check https://github.com/netty/netty-incubator-codec-quic/pull/677
