### ISSUE TITLE
Issue with QuicCodecDispatcher 

### ISSUE THREAD

**Issue by poisonriver** [netty/netty-incubator-codec-quic#710]
Hi @normanmaurer ,
I'm trying to utilize `QuicCodecDispatcher` and noticed that a number of `QuicheQuicChannel` instances are increasing with time on my server (when http clients come and leave) thus creating a leak. I removed `QuicCodecDispatcher` from the server initialization and the problem disappeared. Then I added logging for `QuicChannel` init and Http3 request processing (`Http3RequestStreamInboundHandler.channelRead`) and noticed the following:
- Using Curl: 1 packet come from client during Quic connection establishment (Initial) and 1 `QuichChannel` init call happens
- Using Chrome : 5 packets come from a client during Quic connection establishment (Initial, 0-RTT, 0-RTT, Initial, Initial) and 5 `QuichChannel` init calls happen, while Http3 request is being processed only in one of these `QuicChannel`s.

My server initialization code is below, Wireshark screenshot are attached. Can you please advise if I'm missing something or there's some other issue?
```
        Bootstrap bootstrap = new Bootstrap().group(nioEventLoopGroup)
                .channel(EpollDatagramChannel.class)
                .option(EpollChannelOption.SO_REUSEPORT, true)
                .handler(new QuicCodecDispatcher() {
                    @Override
                    protected void initChannel(Channel channel, int localConnectionIdLength, QuicConnectionIdGenerator idGenerator) throws Exception {
                        QuicServerCodecBuilder codecBuilder = Http3.newQuicServerCodecBuilder()
                                .localConnectionIdLength(localConnectionIdLength)
                                .connectionIdAddressGenerator(idGenerator)
                                .sslContext(sslContext)
                                .maxIdleTimeout(10000, TimeUnit.MILLISECONDS)
                                .handler(new ChannelInitializer<QuicChannel>() {
                                    protected void initChannel(QuicChannel ch) {
                                        log.info("QuicChannel init: " + ch.id());
                                        ch.pipeline().addLast(new Http3ServerConnectionHandler(
                                                new ChannelInitializer<QuicStreamChannel>() {
                                                    @Override
                                                    protected void initChannel(QuicStreamChannel ch) {
                                                        ch.pipeline().addLast(new Http3RequestStreamInboundHandler() {
                                                            @Override
                                                            protected void channelRead(ChannelHandlerContext ctx, Http3HeadersFrame frame) throws Exception {
                                                            }

                                                            @Override
                                                            protected void channelRead(ChannelHandlerContext ctx, Http3DataFrame frame) throws Exception {
                                                            }

                                                            @Override
                                                            protected void channelInputClosed(ChannelHandlerContext ctx) throws Exception {
                                                            }

                                                        });
                                                    }
                                                }, null, null, null, true)
                                        );
                                    }
                                });
                        channel.pipeline().addLast(codecBuilder.build());
                    }
                });
        for (int i = 0; i < threadsPerAddress; i++) {
            Channel quicChannel = bootstrap
                    .bind(address, port).sync().channel();
            quicChannels.add(quicChannel);
        }

```
<img width="1772" alt="curl-codec-dispatcher" src="https://github.com/netty/netty-incubator-codec-quic/assets/25157353/f3cc3eb5-9414-4942-9da9-f471f241eca2">
<img width="1746" alt="chrome-codec-dispatcher" src="https://github.com/netty/netty-incubator-codec-quic/assets/25157353/0917378d-b895-4757-9dfd-2aa046075b65">

**Comment by poisonriver** [comment]
Hi @normanmaurer ,
heap dump (made with option 'live' ) attached
[netty-dump.bin.gz](https://github.com/netty/netty-incubator-codec-quic/files/15025576/netty-dump.bin.gz)

**Comment by normanmaurer** [comment]
Sorry these last few weeks been super busy. I will pick it up next week

**Comment by normanmaurer** [comment]
@poisonriver hmm... in the heap dump I only see 10 `QuicheQuicChannel` instances.

**Comment by normanmaurer** [comment]
@poisonriver I am pretty sure this should fix what you did see https://github.com/netty/netty-incubator-codec-quic/pull/720

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty-incubator-codec-quic/pull/720 and https://github.com/netty/netty-incubator-codec-quic/pull/721

**Comment by poisonriver** [comment]
Hi @normanmaurer ,
Thank you, looks like this is the issue, I will test it soon

> @poisonriver I am pretty sure this should fix what you did see #720

**Comment by normanmaurer** [comment]
@poisonriver keep me posted

**Comment by normanmaurer** [comment]
@poisonriver any updates ?

**Comment by poisonriver** [comment]
> @poisonriver any updates ?

Hi @normanmaurer 
ran some tests, looks like nothing leaks now, thank you!
side question: is there any reason for not exposing initial congestion window from the Quiche config?

**Comment by normanmaurer** [comment]
> > @poisonriver any updates ?
> 
> Hi @normanmaurer ran some tests, looks like nothing leaks now, thank you! side question: is there any reason for not exposing initial congestion window from the Quiche config?
Nope... PRs welcome :)

**Comment by poisonriver** [comment]
> > > @poisonriver any updates ?
> > 
> > 
> > Hi @normanmaurer ran some tests, looks like nothing leaks now, thank you! side question: is there any reason for not exposing initial congestion window from the Quiche config?
> 
> Nope... PRs welcome :)

PR is created
