### ISSUE TITLE
`QuicTokenHandler` receives buffers of different endianness

### ISSUE THREAD

**Issue by makkarpov** [netty/netty-incubator-codec-quic#731]
**Version:** ~0.0.64.Final~  0.0.65.Final

`QuicTokenHandler` receives swapped byte buffer in `writeToken`, but a regular buffer in `validateToken`.

This could give you a lot of debugging time figuring out why none of the `readInt`, `writeInt` and similar functions works correctly.

**Comment by normanmaurer** [comment]
@makkarpov I think we should most likely swap it before we call `writeToken`. Do you want to do a PR ?

**Comment by makkarpov** [comment]
Sure, I can do the PR.

You mean wrap in the `SwappedByteBuf` for the second time? It should not be a big deal in performance terms (since tokens are short), but construction like `SwappedByteBuf(SwappedByteBuf(x))` look awkward. Shouldn't we just remove `allocateNativeOrder` from the allocation of `mintTokenBuffer`? Byte order of this buffer does not seem to be relevant anywhere.

**Comment by normanmaurer** [comment]
Sounds good
