### ISSUE TITLE
Sanity check for QuicServerCodecBuilder options

### ISSUE THREAD

**Issue by valerauko** [netty/netty-incubator-codec-quic#78]
A few days back I accidentally caused it to crash and burn with a rust panic -- but I couldn't repro it with the maven SNAPSHOT. However while playing around with the options trying to remember what I did the other day that broke it (it was a null pointer), I found a different one by setting initialMaxStreamsBidirectional to -1. Trying to initChannel like that resulted in the following:
```
thread '<unnamed>' panicked at 'internal error: entered unreachable code', src/octets.rs:656:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Subprocess failed (exit code: 134)
```
No java stacktrace, and the jvm exited too.

Of course this isn't something one'd do accidentally. Should I put up a pr to add some more option validations?

**Comment by normanmaurer** [comment]
Yes a PR would be awesome to check for negative values etc

**Comment by normanmaurer** [comment]
@valerauko I had a few minutes... Check https://github.com/netty/netty-incubator-codec-quic/pull/79

**Comment by valerauko** [comment]
Awesome, thanks! Sorry I wasn't able to put up a fix quicker...

**Comment by normanmaurer** [comment]
Don't worry ... most important was that you made me aware of it
