### ISSUE TITLE
Quic decouples from TLS

### ISSUE THREAD

**Issue by chenzhiguo** [netty/netty-incubator-codec-quic#82]
QUIC and TLS are a good match, but I don't think they should be coupled. 
For example, the RPC framework for the Intranet, the network environment is secure. Data transmission does not need to be encrypted, which can degrade performance.
So, for a scenario like this, is it currently possible that they are not bound?

**Comment by normanmaurer** [comment]
No its not possible... TLS 1.3 are required by spec. https://www.ietf.org/archive/id/draft-ietf-quic-transport-32.html#name-cryptographic-and-transport
